////
/**
* @@@ START COPYRIGHT @@@
*
* Licensed to the Apache Software Foundation (ASF) under one
* or more contributor license agreements.  See the NOTICE file
* distributed with this work for additional information
* regarding copyright ownership.  The ASF licenses this file
* to you under the Apache License, Version 2.0 (the
* "License"); you may not use this file except in compliance
* with the License.  You may obtain a copy of the License at
*
*   http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing,
* software distributed under the License is distributed on an
* "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
* KIND, either express or implied.  See the License for the
* specific language governing permissions and limitations
* under the License.
*
* @@@ END COPYRIGHT @@@
*/
////

= About This Document
This guide describes how to provision the end-user {project-name} binaries on top of an existing Hadoop environment. This install allows you to store and query data using {project-name}, either via {project-name} clients
(see {docs-url}/client_install/index.html[{project-name} Client Installation Guide]) or via application code you write.

If you want to install a Trafodion developer-build environment, then please refer to the 
http://trafodion.apache.org/contributing-redirect.html[Trafodion Contributor Guide] for instructions.

== Intended Audience
This guide assumes that you are well-versed in Linux and Hadoop administration. If you don't have such experience, then
you should consider going through the steps required to install a Hadoop environment before attempting to install {project-name}.

The instructions contained herein apply to the following environments.

* *Single-Node Environments*: Typically used when you want to evaluate {project-name}.
* *Cluster (Multi-Node) Environments*: Typically used when you deploy {project-name} for application usage.

NOTE: {project-name} can be provisioned on a single-node or multi-node environment. Unless specifically noted, the term *cluster* is used
to mean both single- and multi-node environments.

The provisioning instructions applies to a diverse set of platforms:

* *Virtual Machines*: Often used for evaluations and {project-name} development.
* *Cloud*: Used for Product Environments as well as for Developer Environments.
* *Bare Metal*: Used for Product Environments as well as for Developer Environments.

NOTE: The term *node* is used to represent a computing platform on which operating system, Hadoop, and {project-name} software is running. 
Unless specifically qualified (bare-metal node, virtual-machine node, or cloud-node), *node* represents a computing platform in your cluster
regardless of platform type.

== New and Changed Information
This guide has been updated to include Ambari installation.

<<<
== Notation Conventions
This list summarizes the notation conventions for syntax presentation in this manual.

* UPPERCASE LETTERS
+
Uppercase letters indicate keywords and reserved words. Type these items exactly as shown. Items not enclosed in brackets are required. 
+
```
SELECT
```

* lowercase letters
+
Lowercase letters, regardless of font, indicate variable items that you supply. Items not enclosed in brackets are required.
+
```
file-name
```

* &#91; &#93; Brackets 
+
Brackets enclose optional syntax items.
+
```
DATETIME [start-field TO] end-field
```
+
A group of items enclosed in brackets is a list from which you can choose one item or none.
+
The items in the list can be arranged either vertically, with aligned brackets on each side of the list, or horizontally, enclosed in a pair of brackets and separated by vertical lines.
+
For example: 
+
```
DROP SCHEMA schema [CASCADE]
DROP SCHEMA schema [ CASCADE | RESTRICT ]
```

<<<
* { } Braces 
+
Braces enclose required syntax items.
+
```
FROM { grantee [, grantee ] ... }
```
+ 
A group of items enclosed in braces is a list from which you are required to choose one item.
+
The items in the list can be arranged either vertically, with aligned braces on each side of the list, or horizontally, enclosed in a pair of braces and separated by vertical lines.
+
For example:
+
```
INTERVAL { start-field TO end-field }
{ single-field } 
INTERVAL { start-field TO end-field | single-field }
``` 
* | Vertical Line 
+
A vertical line separates alternatives in a horizontal list that is enclosed in brackets or braces.
+
```
{expression | NULL} 
```

* &#8230; Ellipsis
+
An ellipsis immediately following a pair of brackets or braces indicates that you can repeat the enclosed sequence of syntax items any number of times.
+
```
ATTRIBUTE[S] attribute [, attribute] ...
{, sql-expression } ...
```
+ 
An ellipsis immediately following a single syntax item indicates that you can repeat that syntax item any number of times.
+
For example:
+
```
expression-n ...
```

* Punctuation
+
Parentheses, commas, semicolons, and other symbols not previously described must be typed as shown.
+
```
DAY (datetime-expression)
@script-file 
```
+
Quotation marks around a symbol such as a bracket or brace indicate the symbol is a required character that you must type as shown.
+
For example:
+
```
"{" module-name [, module-name] ... "}"
```

* Item Spacing
+
Spaces shown between items are required unless one of the items is a punctuation symbol such as a parenthesis or a comma.
+
```
DAY (datetime-expression) DAY(datetime-expression)
```
+
If there is no space between two items, spaces are not permitted. In this example, no spaces are permitted between the period and any other items:
+
```
myfile.sh
```

* Line Spacing
+
If the syntax of a command is too long to fit on a single line, each continuation line is indented three spaces and is separated from the preceding line by a blank line.
+
This spacing distinguishes items in a continuation line from items in a vertical list of selections. 
+
```
match-value [NOT] LIKE _pattern
   [ESCAPE esc-char-expression] 
```

== Comments Encouraged
We encourage your comments concerning this document. We are committed to providing documentation that meets your
needs. Send any errors found, suggestions for improvement, or compliments to {project-support}.

Include the document title and any comment, error found, or suggestion for improvement you have concerning this document.
