////
/**
* @@@ START COPYRIGHT @@@
*
* Licensed to the Apache Software Foundation (ASF) under one
* or more contributor license agreements.  See the NOTICE file
* distributed with this work for additional information
* regarding copyright ownership.  The ASF licenses this file
* to you under the Apache License, Version 2.0 (the
* "License"); you may not use this file except in compliance
* with the License.  You may obtain a copy of the License at
*
*   http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing,
* software distributed under the License is distributed on an
* "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
* KIND, either express or implied.  See the License for the
* specific language governing permissions and limitations
* under the License.
*
* @@@ END COPYRIGHT @@@
  */
////

[[activate]]
= Activate

[[activate-manage-trafodion]]
== Manage Trafodion

You use the Trafodion runtime user ID to perform Trafodion management operations.

The following table provides an overview of the different Trafodion management scripts.

[cols="40%,20%l,20%l,20%l",options="header"]
|===
| Component                              | Start     | Stop     | Status
| *All of Trafodion*                     | sqstart   | sqstop   | sqcheck
| *RMS Server*                           | rmsstart  | rmsstop  | rmscheck
| *REST Server*                          | reststart | reststop | -
| *LOB Server*                           | lobstart  | lobstop  | -
| *DCS (Database Connectivity Services)* | dcsstart  | dcsstop  | dcscheck
|===

*Example: Start Trafodion*

```
cd $MY_SQROOT/sql/scripts
sqstart
sqcheck
```

[[activate-validate-trafodion-installation]]
== Validate Trafodion Installation

You can use sqlci (part of the base product) or trafci (requires separate install; see the
http://trafodion.apache.org/docs/client_install/index.html[Trafodion Client Installation Guide]) to validate your installation.

=== Smoke Test
A simple smoke test to validate that Trafodion is functioning.

```
get schemas;
create table table1 (a int);
invoke table1;
insert into table1 values (1), (2), (3), (4);
select * from table1;
drop table table1;
exit;
```

<<<
*Example*

```
$ sqlci
Apache Trafodion Conversational Interface 1.3.0
Copyright (c) 2015 Apache Software Foundation
>>get schemas;

Schemas in Catalog TRAFODION
============================

SEABASE
_MD_
_REPOS_

--- SQL operation complete.
>>create table table1 (a int);

--- SQL operation complete.
>>invoke table1;

-- Definition of Trafodion table TRAFODION.SEABASE.TABLE1
-- Definition current  Mon Feb 15 07:42:02 2016

  (
    SYSKEY                           LARGEINT NO DEFAULT NOT NULL NOT DROPPABLE
      NOT SERIALIZED
  , A                                INT DEFAULT NULL SERIALIZED
  )

--- SQL operation complete.
>>insert into table1 values (1), (2), (3), (4);

--- 4 row(s) inserted.
>>select * from table1;

A
-----------

          1
          2
          3
          4

--- 4 row(s) selected.
>>drop table table1;

--- SQL operation complete.
>>exit;
$
```

<<<
Assuming no errors, your installation has been successful. Next, do the following:

* Install the Trafodion client software. Refer to the http://trafodion.apache.org/docs/client_install/index.html[Trafodion Client Installation Guide].
* Use Trafodion. Refer to the http://trafodion.apache.org/docs/sql_reference/index.html[Trafodion SQL Reference Manual.]
* Review other Trafodion documentation. Refer to the http://trafodion.apache.org/documentation.html[Trafodion documentation].

[[activate-troubleshooting-tips]]
== Troubleshooting Tips

If you are not able to start up the environment or if there are problems running sqlci or trafci, then verify that the all the processes are up and running.

* `sqcheck` should indicate all processes are running.
 
If processes are not running as expected, then:

* `sqstop` to shut down Trafodion. If some Trafodion processes do not terminate cleanly, then run `ckillall`.
* `sqstart` to restart Trafodion.
 
If problems persist please review logs:

* `$MY_SQROOT/logs`: Trafodion logs.
