////
/**
* @@@ START COPYRIGHT @@@
*
* Licensed to the Apache Software Foundation (ASF) under one
* or more contributor license agreements.  See the NOTICE file
* distributed with this work for additional information
* regarding copyright ownership.  The ASF licenses this file
* to you under the Apache License, Version 2.0 (the
* "License"); you may not use this file except in compliance
* with the License.  You may obtain a copy of the License at
*
*   http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing,
* software distributed under the License is distributed on an
* "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
* KIND, either express or implied.  See the License for the
* specific language governing permissions and limitations
* under the License.
*
* @@@ END COPYRIGHT @@@
  */
////

[[install]]
= Install

You download the Trafodion binaries from the Trafodion http://trafodion.apache.org/download.html[Download] page. 
Download the following packages:

* Trafodion Installer (if planning to use the Trafodion Installer)
* Trafodion Server

NOTE: You can download and install the Trafodion Clients once you've installed and activated Trafodion. Refer to the
http://trafodion.apache.org/docs/client_install/index.html[Trafodion Client Install Guide] for instructions.

*Example*

```
$ mkdir $HOME/trafodion-download
$ cd $HOME/trafodion-download
$ Download the Trafodion Installer binarier
$ wget http://traf-builds.esgyn.com/downloads/trafodion/publish/release/1.3.0/apache-trafodion-installer-1.3.0-incubating-bin.tar.gz
--2016-02-14 04:19:40--  http://traf-builds.esgyn.com/downloads/trafodion/publish/release/1.3.0/apache-trafodion-installer-1.3.0-incubating-bin.tar.gz
Resolving traf-builds.esgyn.com... 52.27.79.56
Connecting to traf-builds.esgyn.com|52.27.79.56|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 68813 (67K) [application/x-gzip]
Saving to: "apache-trafodion-installer-1.3.0-incubating-bin.tar.gz"

100%[=====================================================================================================================>] 68,813       124K/s   in 0.5s

2016-02-14 04:19:42 (124 KB/s) - "apache-trafodion-installer-1.3.0-incubating-bin.tar.gz" saved [68813/68813]

$ # Download the Trafodion Server binaries
$ wget http://traf-builds.esgyn.com/downloads/trafodion/publish/release/1.3.0/apache-trafodion-1.3.0-incubating-bin.tar.gz
Resolving traf-builds.esgyn.com... 52.27.79.56
Connecting to traf-builds.esgyn.com|52.27.79.56|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 214508243 (205M) [application/x-gzip]
Saving to: "apache-trafodion-1.3.0-incubating-bin.tar.gz"

100%[=====================================================================================================================>] 214,508,243 3.90M/s   in 55s

2016-02-14 04:22:14 (3.72 MB/s) - "apache-trafodion-1.3.0-incubating-bin.tar.gz" saved [214508243/214508243]

$ ls -l
total 209552
-rw-rw-r-- 1 centos centos 214508243 Jan 12 20:10 apache-trafodion-1.3.0-incubating-bin.tar.gz
-rw-rw-r-- 1 centos centos     68813 Jan 12 20:10 apache-trafodion-installer-1.3.0-incubating-bin.tar.gz
$
```

[[install-trafodion-installer]]
== Trafodion Installer

NOTE: You *must* install log4c&#43;&#43; on all nodes in the cluster prior to running the Trafodion Installer. Refer
to <<prepare-build-and-install-log4cplusplus,Build and Install log4c++>> for instructions.


The Trafodion Installer automates most of the tasks requires to install Trafodion. First, unpack the installation tar file.

*Example*

```
$ mkdir $HOME/trafodion-installer
$ cd $HOME/trafodion-downloads
$ tar -zxf apache-trafodion-installer-1.3.0-incubating-bin.tar.gz -C $HOME/trafodion-installer
$ ls $HOME/trafodion-installer/installer
bashrc_default           tools                             traf_config_check           trafodion_apache_hadoop_install  traf_package_setup
build-version-1.3.0.txt  traf_add_user                     traf_config_setup           trafodion_config_default         traf_setup
dcs_installer            traf_apache_hadoop_config_setup   traf_create_systemdefaults  trafodion_install                traf_sqconfig
rest_installer           traf_authentication_conf_default  traf_getHadoopNodes         trafodion_license                traf_start
setup_known_hosts.exp    traf_cloudera_mods98              traf_hortonworks_mods98     trafodion_uninstaller
$ 
```

The Trafodion Installer supports two different modes:

1. *Guided Setup*: Prompts for information as it works through the installation process. This mode is recommended for new users.
2. *Expert Setup*: Required information is provided in a pre-formatted bash-script configuration file, which is provided
via a command argument when running the Trafodion Installer thereby surpressing all prompts.
+
A template of the configuration file is available here within the installer directory: `trafodion_config_default`.
Make a copy of the file in your directory and populate the needed information.
+
Expert Setup is recommended for the expert user and/or for unattended installs.
Refer to <<install-trafodion-expert-setup,Trafodion Installer: Expert Setup>> for information about how to
populate this file.

[[install-trafodion-installer-usage]]
=== Trafodion Installer: Usage

The following shows help for the Trafodion Installer.

```
./trafodion_install --help

This script will install Trafodion. It will create a configuration
file (if one has not been created), setup of the environment needed
for Trafodion, configure HBase with Hbase-trx and co-processors needed,
and install a specified Trafodion build.

Options:
    --help             Print this message and exit
    --accept_license   If provided, the user agrees to accept all the
                       provisions in the Trafodion license.  This allows
                       for automation by skipping the display and prompt of
                       the Trafodion license.
    --config_file      If provided, all install prompts will be
                       taken from this file and not prompted for.
```

[[install-trafodion-installer-guided-setup]]
=== Trafodion Installer: Guided Setup

You perform this step using the Trafodion Provisioning ID.

The Guided Setup prompts you for the information you collected in the
<<prepare-gather-configuration-information, Gather Configuration Information>> step in the <<prepare,Prepare>> activity.

The following example shows how to install Trafodion a two-node Cloudera Hadoop cluster using Guided Setup.

NOTE: By default, the Trafodion Installer invokes `sqlci` so that you can enter the `initialize tradodion;` command.
This is shown in the example below.

```
$ cd $HOME/trafodion-installer/installer
$ ./trafodion_install

******************************
 TRAFODION INSTALLATION START
******************************

***INFO: testing sudo access
***INFO: Log file located at /var/log/trafodion/trafodion_install_2016-02-15-04-45-30.log
***INFO: Config directory: /etc/trafodion
***INFO: Working directory: /usr/lib/trafodion

*******************************
 Trafodion Configuration Setup
*******************************

***INFO: Please press [Enter] to select defaults.

Enter trafodion password, default is [traf123]: traf123
Enter list of nodes (blank separated), default []: trafodion-1 trafodion-2
Enter Trafodion userid's home directory prefix, default is [/home]: /home
Specify full path to EPEL RPM (including .rpm), default is None:
***INFO: Will attempt to download RPM if EPEL is not installed on all nodes.
Specify location of Java 1.7.0_65 or higher (JDK), default is []: /usr/java/jdk1.7.0_67-cloudera
Enter full path (including .tar or .tar.gz) of trafodion tar file []: /home/centos/trafodion-download/apache-trafodion-1.3.0-incubating-bin.tar.gz
Enter Hadoop admin username, default is [admin]:
Enter Hadoop admin password, default is [admin]:
Enter Hadoop external network URL:port (no 'http://' needed), default is []: trafodion-1.apache.org:7180
Enter HDFS username, default is [hdfs]:
Enter HBase username, default is [hbase]:
Enter HBase group, default is [hbase]:
Enter directory to install trafodion to, default is [/home/trafodion/apache-trafodion-1.3.0-incubating-bin]:
Total number of client connections per node, default [16]: 8
Enable simple LDAP security (Y/N), default is N: N
***INFO: Configuration file: /etc/trafodion/trafodion_config
***INFO: Trafodion configuration setup complete

************************************
 Trafodion Configuration File Check
************************************


The authenticity of host 'trafodion-1 (10.1.30.71)' can't be established.
RSA key fingerprint is 83:96:d4:5e:c1:b8:b1:62:8d:c6:78:a7:7f:1f:6a:d7.
Are you sure you want to continue connecting (yes/no)? yes
***INFO: Testing sudo access on node trafodion-1
***INFO: Testing sudo access on node trafodion-2
***INFO: Testing ssh on trafodion-1
***INFO: Testing ssh on trafodion-2
***INFO: Getting list of all cloudera nodes
***INFO: Getting list of all cloudera nodes
***INFO: cloudera list of nodes:  trafodion-1 trafodion-2
***INFO: Testing ssh on trafodion-1
***INFO: Testing ssh on trafodion-2
***INFO: Testing sudo access on trafodion-1
***INFO: Testing sudo access on trafodion-2
***DEBUG: trafodionFullName=trafodion_server-1.3.0.tgz
***INFO: Trafodion version = 1.3.0
***DEBUG: HBase's java_exec=/usr/java/jdk1.7.0_67-cloudera/bin/java

******************************
 TRAFODION SETUP
******************************

***INFO: Starting Trafodion environment setup (2016-02-15-07-09-58)
=== 2016-02-15-07-09-58 ===
# @@@ START COPYRIGHT @@@
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
.
.
.
and hold each Contributor harmless for any liability incurred by,
or claims asserted against, such Contributor by reason of your
accepting any such warranty or additional liability.

END OF TERMS AND CONDITIONS

BY TYPING "ACCEPT" YOU AGREE TO THE TERMS OF THIS AGREEMENT:ACCEPT
***INFO: testing sudo access
***INFO: Checking all nodes in specified node list
trafodion-1
trafodion-2
***INFO: Total number of nodes = 2
***INFO: Starting Trafodion Package Setup (2016-02-15-07-11-09)
***INFO: Installing required packages
***INFO: Log file located in /var/log/trafodion
***INFO: ... pdsh on node trafodion-1
***INFO: ... pdsh on node trafodion-2
***INFO: Checking if log4cxx is installed ...
***INFO: Checking if sqlite is installed ...
***INFO: Checking if expect is installed ...
***INFO: Installing expect on all nodes
.
.
.
***INFO: modifying limits in /usr/lib/trafodion/trafodion.conf on all nodes
***INFO: create Trafodion userid "trafodion"
***INFO: Trafodion userid's (trafodion) home directory: /home/trafodion
***INFO: testing sudo access
Generating public/private rsa key pair.
Created directory '/home/trafodion/.ssh'.
Your identification has been saved in /home/trafodion/.ssh/id_rsa.
Your public key has been saved in /home/trafodion/.ssh/id_rsa.pub.
The key fingerprint is:
4b:b3:60:38:c9:9d:19:f8:cd:b1:c8:cd:2a:6e:4e:d0 trafodion@trafodion-1
The key's randomart image is:
+--[ RSA 2048]----+
|                 |
|     .           |
|    . . .        |
|   o * X o       |
|  . E X S        |
|   . o + +       |
|    o . o        |
|   o..           |
|   oo            |
+-----------------+
***INFO: creating .bashrc file
***INFO: Setting up userid trafodion on all other nodes in cluster
***INFO: Creating known_hosts file for all nodes
trafodion-1
trafodion-2
***INFO: trafodion user added successfully
***INFO: Trafodion environment setup completed
***INFO: creating sqconfig file
***INFO: Reserving DCS ports

******************************
 TRAFODION MODS
******************************

***INFO: Cloudera installed will run traf_cloudera_mods98
***INFO: Detected JAVA version 1.7
***INFO: copying hbase-trx-cdh5_3-1.3.0.jar to all nodes
***INFO: Cloudera Manager is on trafodion-1
***INFO: Detected JAVA version 1.7
***INFO: copying hbase-trx-cdh5_3-1.3.0.jar to all nodes
***INFO: Cloudera Manager is on trafodion-1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
.
.
.
{
  "id" : 76,
  "name" : "Restart",
  "startTime" : "2016-02-15T07:12:48.511Z",
  "active" : true,
  "children" : {
    "items" : [ {
      "id" : 77,
      "name" : "Stop",
      "startTime" : "2016-02-15T07:12:48.575Z",
      "endTime" : "2016-02-15T07:13:17.139Z",
      "active" : false,
      "success" : true,
      "resultMessage" : "All services successfully stopped."
    }, {
      "id" : 100,
      "name" : "Start",
      "startTime" : "2016-02-15T07:13:17.157Z",
      "active" : true
    } ]
  }
}***INFO: ...polling every 30 seconds until restart is completed.
      "resultMessage" : "All services successfully started."
    } ]
  }
}***INFO: ...polling every 30 seconds until restart is completed.
***INFO: Hadoop restart completed successfully
***INFO: waiting for HDFS to exit safemode
Safe mode is OFF
***INFO: Setting HDFS ACLs for snapshot scan support
***INFO: Trafodion Mods ran successfully.

******************************
 TRAFODION START
******************************

/usr/lib/trafodion/installer/..
***INFO: Log file location /var/log/trafodion/trafodion_install_2016-02-15-07-08-07.log
***INFO: traf_start
******************************************
******************************************
******************************************
******************************************
/home/trafodion/apache-trafodion-1.3.0-incubating-bin
***INFO: untarring build file /usr/lib/trafodion/apache-trafodion-1.3.0-incubating-bin/trafodion_server-1.3.0.tgz to /home/trafodion/apache-trafodion-1.3.0-incubating-bin
.
.
.
******* Generate public/private certificates *******

 Cluster Name : Cluster%201
Generating Self Signed Certificate....
***********************************************************
 Certificate file :server.crt
 Private key file :server.key
 Certificate/Private key created in directory :/home/trafodion/sqcert
***********************************************************

***********************************************************
 Updating Authentication Configuration
***********************************************************
Creating folders for storing certificates

***INFO: copying /home/trafodion/sqcert directory to all nodes
***INFO: copying install to all nodes
***INFO: starting Trafodion instance
Checking orphan processes.
Removing old mpijob* files from /home/trafodion/apache-trafodion-1.3.0-incubating-bin/tmp

Removing old monitor.port* files from /home/trafodion/apache-trafodion-1.3.0-incubating-bin/tmp

Executing sqipcrm (output to sqipcrm.out)
Starting the SQ Environment (Executing /home/trafodion/apache-trafodion-1.3.0-incubating-bin/sql/scripts/gomon.cold)
Background SQ Startup job (pid: 7276)
.
.
.
Zookeeper is listening on port 2181
DcsMaster is listening on port 23400

Process         Configured      Actual          Down
---------       ----------      ------          ----
DcsMaster       1               1
DcsServer       2               2
mxosrvr         8               8


You can monitor the SQ shell log file : /home/trafodion/apache-trafodion-1.3.0-incubating-bin/logs/sqmon.log


Startup time  0 hour(s) 1 minute(s) 9 second(s)
Apache Trafodion Conversational Interface 1.3.0
Copyright (c) 2015 Apache Software Foundation
>> initialize trafodion;
--- SQL operation complete.
>>

End of MXCI Session

***INFO: Installation completed successfully.

*********************************
 TRAFODION INSTALLATION COMPLETE
*********************************
```

Next, switch to the Trafodion Runtime User and check the status of Trafodion.

*Example*

```
$ sudo su - trafodion
$ sqcheck
Checking if processes are up.
Checking attempt: 1; user specified max: 2. Execution time in seconds: 0.

The SQ environment is up!


Process         Configured      Actual      Down
-------         ----------      ------      ----
DTM             2               2
RMS             4               4
MXOSRVR         8               8

$
```

Trafodion is now running on your Hadoop cluster. Please refer to the <<activate,Activate>> chapter for
basic instructions on how to verify the Trafodion management and how to perform basic management
operations.

[[install-trafodion-installer-expert-setup]]
=== Trafodion Installer: Expert Setup

The `--config_file` option runs the Trafodion in Expert Setup mode.

Before running the Trafodion Installer with this option, you do the following:

1. Copy the `trafodion_config_default` file.
+
*Example*
+
```
cp trafodion_config_default my_config
```

2. Edit the new file using the information you collected in the
<<prepare-gather-configuration-information,Gather Configuration Information>>

3. Run the Trafodion Installer in Expert Setup Mode
+
*Example*
+
```
./trafodion_installer --config_file my_config
```

==== Example: Creating a Trafodion Configuration File

Using the instructions in <<prepare-gather-configuration-information,Gather Configuration Information>>,
you recorded the following information.

[cols="15%l,50%,35%",options="header"]
|===
| ID                      | Information                                                                                | Setting                       
| ADMIN                   | Administrator user name for Apache Ambari or Cloudera Manager.                             | admin                         
| BACKUP_DCS_NODES        | List of nodes where to start the backup DCS Master components.                             | 
| CLOUD_CONFIG            | Whether you're installing Trafodion on a cloud environment.                                | N 
| CLOUD_TYPE              | What type of cloud environment you're installing Trafodion on.                             | 
| CLUSTER_NAME            | The name of the Hadoop Cluster.                                                            | Cluster 1
| DCS_BUILD               | Tar file containing the DCS component.                                                     | 
| DCS_PRIMARY_MASTER_NODE | The node where the primary DCS should run.                                                 | 
| DCS_SERVER_PARM         | Number of concurrent client sessions per node.                                             | 8
| ENABLE_HA               | Whether to run DCS in high-availability (HA) mode.                                         | N
| EPEL_RPM                | Location of EPEL RPM. Specify if you don't have access to the Internet.                    | 
| FLOATING_IP             | IP address if running DCS in HA mode.                                                      | 
| HADOOP_TYPE             | The type of Hadoop distribution you're installing Trafodion on.                            | cloudera
| HBASE_GROUP             | Linux group name for the HBASE administative user.                                         | hbase
| HBASE_USER              | Linux user name for the HBASE administative user.                                          | hbase
| HDFS_USER               | Linux user name for the HDFS administative user.                                           | hdfs 
| HOME_DIR                | Root directory under which the `trafodion` home directory should be created.               | /home 
| INIT_TRAFODION          | Whether to automatically initialize the Trafodion database.                                | Y
| INTERFACE               | Interface type used for $FLOATING_IP.                                                      | 
| JAVA_HOME               | Location of Java 1.7.0_65 or higher (JDK).                                                 | /usr/java/jdk1.7.0_67-cloudera
| LDAP_CERT               | Full path to TLS certificate.                                                              | 
| LDAP_HOSTS              | List of nodes where LDAP Identity Store servers are running.                               | 
| LDAP_ID                 | List of LDAP unique identifiers.                                                           | 
| LDAP_LEVEL              | LDAP Encryption Level.                                                                     | 
| LDAP_PASSWORD           | Password for LDAP_USER.                                                                    | 
| LDAP_PORT               | Port used to communicate with LDAP Identity Store.                                         | 
| LDAP_SECURITY           | Whether to enable simple LDAP authentification.                                            | N   
| LDAP_USER               | LDAP Search user name.                                                                     | 
| LOCAL_WORKDIR           | The directory where the Trafodion Installer is located.                                    | /home/centos/trafodion-installer/installer
| MANAGEMENT_ENABLED      | Whether your installation uses separate management nodes.                                  | N
| MANAGEMENT_NODES        | The FQDN names of management nodes, if any.                                                | 
| NODE_LIST               | The FQDN names of the nodes where Trafodion will be installed.                             | trafodion-1 trafodion-2
| PASSWORD                | Administrator password for Apache Ambari or Cloudera Manager.                              | admin
| REST_BUILD              | Tar file containing the REST component.                                                    | 
| SQ_ROOT                 | Target directory for the Trafodion software.                                               | /home/trafodion/apache-trafodion-1.3.0-incubating-bin
| START                   | Whether to start Trafodion after install/upgrade.                                          | Y
| SUSE_LINUX              | Whether your installing Trafodion on SUSE Linux.                                           | false
| TRAF_PACKAGE            | The location of the Trafodion installation package tar file or core installation tar file. | /home/centos/trafodion-download/apache-trafodion-1.3.0-incubating-bin.tar.gz
| TRAF_USER               | The Trafodion runtim user ID. Must be `trafodion` in this release.                         | trafodion
| TRAF_USER_PASSWORD      | The password used for the `trafodion:trafodion` user ID.                                   | traf123
| URL                     | FQDN and port for the Distribution Manager's REST API.                                     | trafodion-1.apache.org:7180
|===

Using the information above, you edit `my_config` to contain the following:

```
#!/bin/bash
# @@@ START COPYRIGHT @@@
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# @@@ END COPYRIGHT @@@

#====================================================
# Trafodion Configuration File
# This file contains default values for the installer.

# Users can also edit this file and provide values for all parameters
# and then specify this file on the run line of trafodion_install.
# Example:
# ./trafodion_install --config_file <Trafodion-config-file>
# WARNING: This mode is for advanced users!
#
#=====================================================


#=====================================================
#Must be set to 'true' if on a SUSE linux system. If on another type of system
#this must be set to false.

export SUSE_LINUX="false"

# The working directory where Trafodion installer untars files, etc.
# do not change this unless you really know what you are doing
export TRAF_WORKDIR="/usr/lib/trafodion"

# This is the directory where the installer scripts were untarred to
export LOCAL_WORKDIR="/home/centos/trafodion-installer/installer"

# The maximum number of dcs servers, i.e. client connections
export DCS_SERVERS_PARM="8"

# "true" if this is an upgrade
export UPGRADE_TRAF="false"

# Trafodion userid, This is the userid the Trafodion instance will run under
export TRAF_USER="trafodion"

# Trafodion userid's password
export TRAF_USER_PASSWORD="traf123"

# a blank separated list of nodes in your cluster
# node names should include full domain names
#This can not be left blank!
export NODE_LIST="trafodion-1 trafodion-2"

# count of nodes in node list
export node_count="2"

# another list of the same nodes in NODE_LIST but specified in a pdsh usable format
# i.e.  "-w centos-cdh[1-6]"  or "-w node1 -w node2 -w node3"
export MY_NODES="-w trafodion-[1-2]"

# the directory prefix for the trafodion userid's $HOME directory
# i.e. /opt/home, not /opt/home/trafodion
export HOME_DIR="/home"

#JAVA HOME must be a JDK. Must include FULL Path. Must be 1.7.0_65 or higher.

export JAVA_HOME="/usr/java/jdk1.7.0_67-cloudera"

# If your machine doesn't have external internet access then you must
# specify the location of the EPEL rpm, otherwise leave blank and it
# will be installed from the internet
export EPEL_RPM=""

# full path of the Trafodion package tar file
export TRAF_PACKAGE="/home/centos/trafodion-download/apache-trafodion-1.3.0-incubating-bin.tar.gz"

# if TRAF_PACKAGE wasn't specified then these two values must be specified
# TRAF_BUILD is the trafodion_server tar file
# DCS_BUILD is the DCS tar file
# REST_BUILD is the REST tar file
export TRAF_BUILD=""
export DCS_BUILD=""
export REST_BUILD=""
# Either "cloudera" or "hortonworks" (all lowercase)
export HADOOP_TYPE="cloudera"

# The URL for Cloudera/Hortonworks REST API (i.e. node1.hp.com:8080)
export URL="trafodion-1.apache.org:7180"

# Cloudera/Hortonworks UI admin's userid and password
export ADMIN="admin"
export PASSWORD="admin"

# hadoop cluster name
export CLUSTER_NAME=""

# the Hadoop HDFS userid
export HDFS_USER="hdfs"

# the Hadoop HBase userid and group
export HBASE_USER="hbase"
export HBASE_GROUP="hbase"

# The hadoop HBase service name
export HBASE="hbase"

# full path of where to install Trafodion to
# Example is used below. If $HOME_DIR or $TRAF_USER have been changed
# then this will need to be changed.
# On an upgrade, it is recommend to choose a different directory.
# First time install : /home/trafodion/traf
# On Upgrade: /home/trafodion/traf_<date>
# By doing this the previous version will remain and allow for an easier rollback.
export SQ_ROOT="/home/trafodion/apache-trafodion-1.3.0-incubating-bin"

# Start Trafodion after install completes
export START="Y"

# initialize trafodion after starting
export INIT_TRAFODION="Y"

# full path to the sqconfig file
# Default is to leave as is and this file will be created.
export SQCONFIG=""

export CONFIG_COMPLETE="true"

#Turn on simple security. MUST have existing LDAP configured.
export LDAP_SECURITY="N"

#Name of LDAP Config file
export LDAP_AUTH_FILE="traf_authentication_config_${HOSTNAME}"
```

Once completed, run the Trafodion Installer with the `--config_file` option.

*Example*

```
$ ./trafodion_installer --config_file my_config
******************************
 TRAFODION INSTALLATION START
******************************

***INFO: testing sudo access
***INFO: Log file located at /var/log/trafodion/trafodion_install_2016-02-15-08-00-59.log
***INFO: Config directory: /etc/trafodion
***INFO: Working directory: /usr/lib/trafodion

************************************
 Trafodion Configuration File Check
************************************


***INFO: Testing sudo access on node trafodion-1
***INFO: Testing sudo access on node trafodion-2
***INFO: Testing ssh on trafodion-1
***INFO: Testing ssh on trafodion-2
.
.
.
9. Accepting Warranty or Additional Liability. While redistributing
the Work or Derivative Works thereof, You may choose to offer, and
charge a fee for, acceptance of support, warranty, indemnity, or
other liability obligations and/or rights consistent with this
License. However, in accepting such obligations, You may act only
on Your own behalf and on Your sole responsibility, not on behalf
of any other Contributor, and only if You agree to indemnify, defend,
and hold each Contributor harmless for any liability incurred by,
or claims asserted against, such Contributor by reason of your
accepting any such warranty or additional liability.

END OF TERMS AND CONDITIONS

BY TYPING "ACCEPT" YOU AGREE TO THE TERMS OF THIS AGREEMENT:ACCEPT
***INFO: testing sudo access
***INFO: Checking all nodes in specified node list
trafodion-1
trafodion-2
***INFO: Total number of nodes = 2
***INFO: Starting Trafodion Package Setup (2016-02-15-08-02-42)
***INFO: Installing required packages
***INFO: Log file located in /var/log/trafodion
***INFO: ... pdsh on node trafodion-1
***INFO: ... pdsh on node trafodion-2
***INFO: Checking if log4cxx is installed ...
.
.
.
Version Check: done

Metadata Upgrade: done


--- SQL operation complete.
>>

End of MXCI Session

***INFO: Installation completed successfully.

*********************************
 TRAFODION INSTALLATION COMPLETE
*********************************
$ 
```
Next, switch to the Trafodion Runtime User and check the status of Trafodion.

*Example*

```
$ sudo su - trafodion
$ sqcheck
Checking if processes are up.
Checking attempt: 1; user specified max: 2. Execution time in seconds: 0.

The SQ environment is up!


Process         Configured      Actual      Down
-------         ----------      ------      ----
DTM             2               2
RMS             4               4
MXOSRVR         8               8

$
```

Trafodion is now running on your Hadoop cluster. Please refer to the <<activate,Activate>> chapter for
basic instructions on how to verify the Trafodion management and how to perform basic management
operations.

[[install-recipe-based-provisioning]]
== Recipe-Based Provisioning
To be written.
