////
/**
* @@@ START COPYRIGHT @@@
*
* Licensed to the Apache Software Foundation (ASF) under one
* or more contributor license agreements.  See the NOTICE file
* distributed with this work for additional information
* regarding copyright ownership.  The ASF licenses this file
* to you under the Apache License, Version 2.0 (the
* "License"); you may not use this file except in compliance
* with the License.  You may obtain a copy of the License at
*
*   http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing,
* software distributed under the License is distributed on an
* "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
* KIND, either express or implied.  See the License for the
* specific language governing permissions and limitations
* under the License.
*
* @@@ END COPYRIGHT @@@
  */
////

[[upgrade]]
= Upgrade

This chapter describes how to use the Trafodion Installer to upgrade Trafodion. You use the Trafodion Provisioning ID
to run the Trafodon Installer.

[[upgrade-guided-upgrade]]
== Guided Upgrade

The Trafodion Installer prompts you for the information you collected in the
<<prepare-gather-configuration-information, Gather Configuration Information>> step in the <<prepare,Prepare>> chapter.

The following example shows a guided upgrade of Trafodion on a two-node Cloudera Hadoop cluster.

*To be written.*

[[upgrade-expert-upgrade]]
=== Expert Upgrade

The `--config_file` option runs the Trafodion in Expert Setup mode. Refer to <<introduction-trafodion-installer,Trafodion Installer>>
in the <<introduction,Introduction>> chapter for instructions of how you edit your configuration file.

TODO: Do you perform an upgrade when the Hadoop configuration changes?

If needed (TODO: when?), edit your config file using the information you collected in the <<prepare-gather-configuration-information,Gather Configuration Information>>
in the <<prepare,Prepare>> chapter. 

The following example shows a guided install of Trafodion on a two-node Cloudera Hadoop cluster.

*To be written.*

