////
/**
* @@@ START COPYRIGHT @@@
*
* Licensed to the Apache Software Foundation (ASF) under one
* or more contributor license agreements.  See the NOTICE file
* distributed with this work for additional information
* regarding copyright ownership.  The ASF licenses this file
* to you under the Apache License, Version 2.0 (the
* "License"); you may not use this file except in compliance
* with the License.  You may obtain a copy of the License at
*
*   http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing,
* software distributed under the License is distributed on an
* "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
* KIND, either express or implied.  See the License for the
* specific language governing permissions and limitations
* under the License.
*
* @@@ END COPYRIGHT @@@
*/
////

[[upgrade]]
= Upgrade

This chapter describes how to use the {project-name} Installer to upgrade {project-name}. You use the {project-name} Provisioning ID
to run the {project-name} Installer.

[[upgraded-download-updated-trafodion-binaries]]
== Download Updated {project-name} Binaries

You perform this step as the {project-name} Provisioning User.

You download the updated {project-name} binaries from the {project-name} {download-url}[Download] page. 
Download the following packages:

* {project-name} Installer (if planning to use the {project-name} Installer)
* {project-name} Server

Refer to <<prepare-download-trafodion-binaries, Download {project-name} Binaries>> in the <<prepare,Prepare>> chapter for examples.


[[upgrade-unpack-installer]]
== Unpack Installer

You perform this step as the {project-name} Provisioning User.

You unpack the updated {project-name} Installer into a new directory.

*Example*

```
$ mkdir $HOME/trafodion-installer
$ cd $HOME/trafodion-downloads
$ tar -zxf apache-trafodion-pyinstaller-2.2.0.tar.gz -C $HOME/trafodion-installer
$
```

[[upgrade-stop-tradodion]]
== Stop {project-name}
You perform this step as the {project-name} Runtime User.

*Example*

```
$ sudo su trafodion
$ sqstop
Shutting down the REST environment now
stopping rest.
Shutting down the DCS environment now
stopping master.
trafodion-1: stopping server.
trafodion-2: stopping server.
stopped $zlobsrv0
stopped $zlobsrv1
Shutting down (normal) the SQ environment!
Wed Feb 17 05:12:40 UTC 2016
Processing cluster.conf on local host trafodion-1
[$Z000KAE] Shell/shell Version 1.0.1 Apache_Trafodion Release 1.3.0 (Build release [1.3.0-0-g5af956f_Bld2], date 20160112_1927)
[$Z000KAE] %ps
[$Z000KAE] NID,PID(os)  PRI TYPE STATES  NAME        PARENT      PROGRAM
[$Z000KAE] ------------ --- ---- ------- ----------- ----------- ---------------
[$Z000KAE] 000,00064198 000 WDG  ES--A-- $WDG000     NONE        sqwatchdog
[$Z000KAE] 000,00064199 000 PSD  ES--A-- $PSD000     NONE        pstartd
[$Z000KAE] 000,00064212 001 GEN  ES--A-- $TSID0      NONE        idtmsrv
[$Z000KAE] 000,00064242 001 DTM  ES--A-- $TM0        NONE        tm
[$Z000KAE] 000,00065278 001 GEN  ES--A-- $ZSC000     NONE        mxsscp
[$Z000KAE] 000,00065305 001 SSMP ES--A-- $ZSM000     NONE        mxssmp
[$Z000KAE] 000,00001219 001 GEN  ES--A-- $Z0000ZU    NONE        mxosrvr
[$Z000KAE] 000,00001235 001 GEN  ES--A-- $Z00010A    NONE        mxosrvr
[$Z000KAE] 000,00001279 001 GEN  ES--A-- $Z00011J    NONE        mxosrvr
[$Z000KAE] 000,00001446 001 GEN  ES--A-- $Z00016B    NONE        mxosrvr
[$Z000KAE] 000,00024864 001 GEN  ES--A-- $Z000KAE    NONE        shell
[$Z000KAE] 001,00025180 000 PSD  ES--A-- $PSD001     NONE        pstartd
[$Z000KAE] 001,00025179 000 WDG  ES--A-- $WDG001     NONE        sqwatchdog
[$Z000KAE] 001,00025234 001 DTM  ES--A-- $TM1        NONE        tm
[$Z000KAE] 001,00025793 001 GEN  ES--A-- $ZSC001     NONE        mxsscp
[$Z000KAE] 001,00025797 001 SSMP ES--A-- $ZSM001     NONE        mxssmp
[$Z000KAE] 001,00026587 001 GEN  ES--A-- $Z010LPM    NONE        mxosrvr
[$Z000KAE] 001,00026617 001 GEN  ES--A-- $Z010LQH    NONE        mxosrvr
[$Z000KAE] 001,00026643 001 GEN  ES--A-- $Z010LR8    NONE        mxosrvr
[$Z000KAE] 001,00026644 001 GEN  ES--A-- $Z010LR9    NONE        mxosrvr
shutdown
[$Z000KAE] %shutdown
exit
Issued a 'shutdown normal' request

Shutdown in progress

# of SQ processes: 0
SQ Shutdown (normal) from /home/trafodion Successful
Wed Feb 17 05:12:47 UTC 2016
$
```

<<<
[[upgrade-guided-upgrade]]
== Guided Upgrade

You perform this step as the {project-name} Provisioning User.

As in the case with an installation, the {project-name} Installer prompts you for the information you collected in the
<<prepare-gather-configuration-information, Gather Configuration Information>> step in the <<prepare,Prepare>> chapter.

From user's perspective, guided upgrade doesn't require the {project-name} runtime user's password. The rest of things have no difference with guided install.
Please refer to <<install-guided-install, Guided Install>> for the *example* of installing {project-name} on a two-node Cloudera Hadoop cluster.


<<<
[[upgrade-automated-upgrade]]
== Automated Upgrade

You perform this step as the {project-name} Provisioning User.

The `--config-file` option runs the {project-name} in Automated Setup mode. Refer to <<introduction-trafodion-installer,{project-name} Installer>>
in the <<introduction,Introduction>> chapter for instructions of how you edit your configuration file.

At a minimum, you need to change the following settings:

* `traf_package`

*Example*

```
$ cd $HOME/trafodion-configuration
$ cp my_config my_config_2.0
$ # Pre edit content

traf_package = "/home/centos/trafodion-download/apache-trafodion-2.2.0.tar.gz"

$ # Use your favorite editor to modify my_config_2.0
$ emacs my_config_2.0
$ # Post edit changes

traf_package = "/home/centos/trafodion-download/apache-trafodion-2.2.0.tar.gz"
```

NOTE: The {project-name} Installer performs the same configuration changes as it does for an installation,
including restarting Hadoop services.

Please refer to <<install-automated-install, Automated Install>> for the *example* of installing {project-name} on a two-node Cloudera Hadoop cluster.
