#!/bin/bash
# @@@ START COPYRIGHT @@@
#
# (C) Copyright 2014 Hewlett-Packard Development Company, L.P.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
# @@@ END COPYRIGHT @@@

#This script will uninstall MapR

#==============================================
function print_usage {
cat << EOF
This script will uninstall Hortonworks.

Usage: $(basename $0) [options]

Options:
    --help                 Print this message and exit.
    --nodes "<node_list>"  -w separated list of nodes (within quotes)

EOF
}
#==============================================
# Parse input parameters
while [[ $# -gt 0 ]]; do
    case "$1" in
         --nodes)
             if [[ -z "$2" ]]; then
                echo "***ERROR: No value passed to param $1."
                print_usage
                exit -1
             fi
             MY_NODES=$2
             shift
             ;;
         --help)
             print_usage
             exit -1
             ;;
         *)
             echo "***ERROR: unknown parameter '$1'"
             exit -1
    esac
    shift
done
#==============================================
#Check with user if they want to preform the uninstall
echo -n "Do you want to uninstall MapR (deleting all data) Y/N: "
read v

if [[ $v != "Y" ]] && [[ $v != "y" ]]; then
   echo "***INFO: Exiting..."
   exit
fi

if [[ $MY_NODES == "" ]]; then
   MY_NODES=$(cat ../../my_nodes)
fi

echo $MY_NODES
exit
#==============================================
echo
echo "***INFO: Uninstalling MapR"
echo
#Stop the Warden on all nodes
pdsh $MY_NODES service mapr-warden stop

#Stop ZooKeeper on all nodes
pdsh $MY_NODES service mapr-zookeeper stop

#Delete all mapr-core* files
pdsh $MY_NODES yum --assumeyes erase mapr-core*

#Delete all mapr-zk-internal* files
pdsh $MY_NODES yum --assumeyes erase mapr-zk-internal*

#Delete /opt/mapr directory and all files within
pdsh $MY_NODES rm -rf /opt/mapr

#Delete /opt/storagefile and /opt/mapr-setup
pdsh $MY_NODES rm /opt/storagefile
pdsh $MY_NODES rm /opt/mapr-setup

#==============================================
echo
echo "***INFO: MapR uninstall complete"
echo
