#! /bin/sh
# @@@ START COPYRIGHT @@@
#
# (C) Copyright 2010-2014 Hewlett-Packard Development Company, L.P.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
# @@@ END COPYRIGHT @@@


fil=$1
if [ "$fil" = "" ]; then
  echo "Usage: $0 filename"
  exit 1
fi

sed "
s/ET:.*/ET:xxxxxxxxxx/g
s/hash2 partitioned.*ways on/hash2 partitioned N ways on/g
s/\(esp_exchange.*\)[1-9](hash2):[1-9]/\1 N(hash2):M/g
s/\(esp_exchange.*\)1:[1-9](hash2)/\1 1:N(hash2)/g
s/\(esp_exchange.*\)(range):[1-9](hash2)/\1 (range):N(hash2)/g
" $fil
