////
/**
 *@@@ START COPYRIGHT @@@
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * @@@ END COPYRIGHT @@@
 */
////

[[sample-programs-accessing-clob-and-blob-data]]
= Sample Programs Accessing CLOB and BLOB Data

This appendix shows two working programs.

[[sample-program-accessing-clob-data]]
== Sample Program Accessing CLOB Data

This sample program shows operations that can be performed through the
Clob interface or through the PreparedStatement interface. The sample
program shows examples of both interfaces taking a variable and putting
the variable's value into a base table that has a CLOB column.

You can access the source at: http://trafodion.apache.org/docs/jdbct4ref_guide/resources/source/clob_example.java

[source, java]
----
include::{sourcedir}/clob_example.java[CLOB Example]
----

[[sample-program-accessing-blob-data]]
== Sample Program Accessing BLOB Data

This sample program shows the use of both the Blob interface and the
PreparedStatement interface to take a byte variable and put the
variable's value into a base table that has a BLOB column.

You can access the source at: http://trafodion.apache.org/docs/jdbct4ref_guide/resources/source/blob_example.java

[source, java]
----
include::{sourcedir}/blob_example.java[BLOB Example]
----

