!
! @@@ START COPYRIGHT @@@
!
! Licensed to the Apache Software Foundation (ASF) under one
! or more contributor license agreements.  See the NOTICE file
! distributed with this work for additional information
! regarding copyright ownership.  The ASF licenses this file
! to you under the Apache License, Version 2.0 (the
! "License"); you may not use this file except in compliance
! with the License.  You may obtain a copy of the License at
!
!   http://www.apache.org/licenses/LICENSE-2.0
!
! Unless required by applicable law or agreed to in writing,
! software distributed under the License is distributed on an
! "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
! KIND, either express or implied.  See the License for the
! specific language governing permissions and limitations
! under the License.
!
! @@@ END COPYRIGHT @@@
!

! Test TM sync requests with collisions
!
exec {type dtm,nowait,nid 2,out TM02.lst}testtm
exec {type dtm,nowait,name $TM01, nid 1,out TM01.lst}testtm
exec {type dtm,nowait,nid 0,out TM00.lst}testtm
delay 5
ps {DTM}

! Start Test3 - No collision commit test
event {DTM} 3
delay 5

! Start Test4 - No collision abort test
event {DTM} 4
delay 5

! Start Test5 - Collision commit test
event {DTM} 5
delay 40 

! Start Test6 - Collision abort test
event {DTM} 6
delay 40 
 
! Start Test7 - Dead TM test
event {DTM} 7
delay 10
exit !
