!
! @@@ START COPYRIGHT @@@
!
! Licensed to the Apache Software Foundation (ASF) under one
! or more contributor license agreements.  See the NOTICE file
! distributed with this work for additional information
! regarding copyright ownership.  The ASF licenses this file
! to you under the Apache License, Version 2.0 (the
! "License"); you may not use this file except in compliance
! with the License.  You may obtain a copy of the License at
!
!   http://www.apache.org/licenses/LICENSE-2.0
!
! Unless required by applicable law or agreed to in writing,
! software distributed under the License is distributed on an
! "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
! KIND, either express or implied.  See the License for the
! specific language governing permissions and limitations
! under the License.
!
! @@@ END COPYRIGHT @@@
!

! Test to register and cancel process death
! notices from non parent process.
!
exec {nowait,name $serv0, out serv0.lst} server waitforclose
exec {nowait,name $serv1, out serv1.lst} server waitforclose
exec {nowait,nid 0,name $TM00,out tm00.lst} server waitforclose
exec {nowait,nid 1,name $TM01,out tm01.lst} server waitforclose
exec {nowait,nid 2,name $TM02,out tm02.lst} server waitforclose
ps
exec {nid 0} notify
