/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_trafodion_jdbc_t2_SQLMXClobWriter */

#ifndef _Included_org_apache_trafodion_jdbc_t2_SQLMXClobWriter
#define _Included_org_apache_trafodion_jdbc_t2_SQLMXClobWriter
#ifdef __cplusplus
extern "C" {
#endif
#undef org_apache_trafodion_jdbc_t2_SQLMXClobWriter_WRITE_BUFFER_SIZE
#define org_apache_trafodion_jdbc_t2_SQLMXClobWriter_WRITE_BUFFER_SIZE 1024L
/*
 * Class:     org_apache_trafodion_jdbc_t2_SQLMXClobWriter
 * Method:    writeChunk
 * Signature: (Ljava/lang/String;JJLjava/lang/String;Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_org_apache_trafodion_jdbc_t2_SQLMXClobWriter_writeChunk
  (JNIEnv *, jobject, jstring, jlong, jlong, jstring, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
