////
/**
 *@@@ START COPYRIGHT @@@
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * @@@ END COPYRIGHT @@@
 */
////

[[deploy-spj-jar-files]]
= Deploy SPJ JAR Files

After developing and packaging the SPJ code into JAR files, you must
move the JAR files from the client workstation to the Trafodion database.

You can upload a SPJ JAR file and create a library by using
the ADD LIBRARY command in the Trafodion Command Interface (trafci).
You use the CREATE LIBRARY, ALTER LIBRARY, and DROP LIBRARY commands.

Libraries provide greater security for JAR files because libraries are
database objects whose access is controlled using standard SQL security.

Deploying a JAR file to a Trafodion instance requires creating a library,
and users must have the required privileges for creating libraries in order
to deploy JAR files.

See these instructions:

* <<create-a-library, Create a Library>>
* <<alter-a-library, Alter a Library>>
* <<drop-a-library, Drop a Library>>
* <<download-a-jar-file-from-a-library, Download a JAR File From a Library>>
* <<display-libraries-and-their-properties, Display Libraries and Their Properties>>

Before you start, see
<<required-privileges-for-creating-altering-or-dropping-a-library, "Required Privileges for Creating, Altering, or Dropping a Library">>.


== Required Privileges for Creating, Altering, or Dropping a Library

Deploying a JAR file to the Trafodion database requires creating a
library, and you must have the required privileges for creating
libraries in order to deploy a JAR file. To create a library in a
schema, you must have both the CREATE_LIBRARY component privilege and
the CREATE_LIBRARY schema-level privilege for the schema. For more
information, see the requirements in <<create-a-library, Create a Library>>.

To alter a library in a schema, you must have both the UPDATE privilege
for the library and the ALTER_LIBRARY privilege for the schema. For more
information, see the requirements in
<<alter-a-library, Alter a Library>>.

To drop a library from a schema, you must have the DROP_LIBRARY
privilege for the schema. For more information, see the requirements in
<<drop-a-library, Drop a Library>>.

To download a JAR file from a library, you must have the CREATE_LIBRARY
component privilege. For more information, see the requirements in
<<download-a-jar-file-from-a-library, Download a JAR File From a Library>>.

[[create-a-library]]
== Create a Library

Refer to the
http://trafodion.apache.org/docs/sql_reference/index.html[Trafodion SQL Reference Manual]
for full documentation of the
http://trafodion.apache.org/docs/sql_reference/index.html#create_library_statement[CREATE LIBRARY]
statement.

When you create a library, HPDM simultaneously uploads an SPJ JAR file
from the client workstation to the Trafodion database and creates a
library for the JAR file in a schema of the database.

Requirements:

* You must have the CREATE_LIBRARY privilege for the SQL_OPERATIONS
component. For more information, see the component privileges in the _HP
Database Manager (HPDM) User Guide_ or the online help in HPDM.
* You must either be the owner of the schema where you will create the
library or have the CREATE_LIBRARY privilege for the schema to create
the library. The schema owner can grant such a schema-level privilege to
other users or roles. For more information, see the

Grant/Revoke Privileges Tool in HPDM or the GRANT SCHEMA statement in the
http://trafodion.apache.org/docs/sql_reference/index.html#grant_statement[Trafodion SQL Reference Manual].

* The JAR file that you select for the library must contain valid Java
bytecode and must not be used by another library in the catalog.
* The JAR file that you select for the library must not exceed a size
threshold if one has been set for HPDM's internal WMS service, the data
source, or the system defaults.

For example, if the CONTROL QUERY DEFAULT (CQD) `POS_ABSOLUTE_MAX_TABLE_SIZE`
has been set for the `HPS_MANAGEABILITY` service, it limits the size
of JAR files that can be uploaded by HPDM. If the JAR file's size
exceeds the threshold, a warning message is displayed, and the file is
not uploaded. By default, this CQD is not set for HPDM's internal WMS
service, the data source, or the system defaults, and HPDM allows you to
upload JAR files of any size.

To upload a JAR file and create a library for the JAR file in a schema:

1.  In HPDM, select the Database area.
2.  In the navigation tree pane, expand the tree to display the folders
of the schema where you want to create the library.
3.  Right-click the Libraries folder, and select Create Library. The
Create Library dialog box appears. For more information, see
<<use-the-create-library-dialog-box, Use the Create Library Dialog Box>>.
4.  In the Create Library dialog box, enter a name for the library.
+
The name must be unique among the libraries in the schema and must not
exceed 128 characters. The library name is not case-sensitive.
+
For example, if you enter `Payroll` as the library name, the database engine
stores the library as `_catalog-name_._schema-name_.PAYROLL`. The database engine
automatically qualifies the library name with the name of the catalog
and schema in which you are creating the library.

5.  Click the [ Browse ] button to locate and select a JAR file on the
client workstation. The *Select a code file* dialog box appears.

6.  In the *Select a code file* dialog box, locate and select the JAR
file on the client workstation, and click [ Open ] to return to the
Create Library dialog box. The Create Library dialog box displays the
full path of the JAR file in the Code File field.

7.  Click [ Create ] to create the library, or click [ Close ] to quit
the dialog box without creating the library.
+
If you click [ Create ], HPDM validates the JAR file, uploads the JAR
file, and creates a library for the JAR file in the schema.

8.  When notified that the library was created successfully, click [ OK ].
9.  To upload another JAR file and create a library, repeat steps 4
through 8.
10.  When you are done uploading JAR files and creating libraries, click
the [ Close ] button to quit the Create
Library dialog box and return to the HPDM main window.

*Related Topics*

* <<use-the-create-library-dialog-box, Use the Create Library Dialog Box>>
* <<alter-a-library, Alter a Library>>
* <<drop-a-library, Drop a Library>>
* <<download-a-jar-file-from-a-library, Download a JAR File From a Library>>
* <<display-libraries-and-their-properties, Display Libraries and Their Properties>>

[[use-the-create-library-dialog-box]]
== Use the Create Library Dialog Box

The Create Library dialog box allows you to upload an SPJ JAR file from
the client workstation to the Trafodion database and create a library for
the JAR file in a schema of the database.

Requirements:

* You must have the CREATE_LIBRARY privilege for the SQL_OPERATIONS
component. For more information, see the component privileges in the _HP
Database Manager (HPDM) User Guide_ or the online help in HPDM.

* You must either be the owner of the schema where you will create the
library or have the CREATE_LIBRARY privilege for the schema to create
the library. The schema owner can grant such a schema-level privilege to
other users or roles. For more information, see the Grant/Revoke
Privileges Tool in HPDM or the GRANT SCHEMA statement in the
http://trafodion.apache.org/docs/sql_reference/index.html[Trafodion SQL Reference Manual].

* The JAR file that you select for the library must contain valid Java
bytecode and must not be used by another library in the catalog.

* The JAR file that you select for the library must not exceed a size
threshold if one has been set for HPDM's internal WMS service, the data
source, or the system defaults.

For example, if the CONTROL QUERY DEFAULT (CQD) `POS_ABSOLUTE_MAX_TABLE_SIZE`
has been set for the HPS_MANAGEABILITY service, it will limit the size
of JAR files that can be uploaded by HPDM.

If the JAR file's size exceeds the threshold, then a warning message is displayed,
and the file is not uploaded. By default, this CQD is not set for HPDM's internal WMS
service, the data source, or the system defaults, and HPDM allows you to
upload JAR files of any size.

[cols="20%,30%,50%",options="header",]
|===
| Group Box    | Control or Field | Description or Action
| *Library*    | Catalog          | Name of the catalog where the library is created. This is a read-only field.
|              | Schema           | Name of the schema where the library is created. This is a read-only field.
|              | Library Name     | Enter a name for the library. The name must be unique among the  libraries
in the schema and must not exceed 128 characters. The library name is not case-sensitive. +
 +
For example, if you enter Payroll as the library name, the database engine stores the library as
`_catalog-name_._schema-name_.PAYROLL`. The database engine automatically qualifies the library name with the
name of the catalog and schema in which you are creating the library.
| *Code File* | Code File         | Click [ Browse ] to launch the *Select a code file* dialog box and
navigate to a JAR file on the client workstation.
|             | [ Create ]        | Creates the library.
|             | [ Close ]         | Closes the dialog box without creating a library.
|             | [ Help ]          | Displays context-sensitive help for this dialog box.
|===

*Related Topics*

* <<create-a-library, Create a Library>>
* <<alter-a-library, Alter a Library>>
* <<drop-a-library, Drop a Library>>
* <<download-a-jar-file-from-a-library, Download a JAR File From a Library>>

[[alter-a-library]]
== Alter a Library

When you alter a library, you can change the underlying JAR file of the library.

Requirements:

* You must have been granted the UPDATE privilege for the library. For
more information, see the Grant/Revoke Privileges Tool in HPDM or the
GRANT LIBRARY statement in the
http://trafodion.apache.org/docs/sql_reference/index.html#grant_statement[Trafodion SQL Reference Manual].

* You must either be the owner of the schema where you're altering the
library or have the ALTER_LIBRARY privilege for the schema to alter the
library. The schema owner can grant such a schema-level privilege to
other users or roles. For more information, see the Grant/Revoke
Privileges Tool in HPDM or the GRANT SCHEMA statement in the
http://trafodion.apache.org/docs/sql_reference/index.html#grant_statement[Trafodion SQL Reference Manual].

* The JAR file that you select for the library must contain valid Java
bytecode and must not be used by another library in the catalog.

* The JAR file that you select for the library must not exceed a size
threshold if one has been set for HPDM's internal WMS service, the data
source, or the system defaults.

For example, if the CONTROL QUERY DEFAULT (CQD) `POS_ABSOLUTE_MAX_TABLE_SIZE`
has been set for the HPS_MANAGEABILITY service, then it limits the size
of JAR files that can be uploaded by HPDM. If the JAR file's size
exceeds the threshold, a warning message is displayed, and the file is
not uploaded. By default, this CQD is not set for HPDM's internal WMS
service, the data source, or the system defaults, and HPDM allows you to
upload JAR files of any size.

To alter a library and change its underlying JAR file:

1.  In HPDM, select the Database area.
2.  In the navigation tree pane, expand the tree to display the folders
of the schema that contains the library, and expand the Libraries folder
to display the libraries within it.
3.  Right-click the name of the library, and select Alter Library. If
you selected a system library, a dialog box appears warning you that you
cannot alter a system library. If you selected a user library, the Alter
Library dialog box appears. For more information, see
<<use-the-alter-library-dialog-box, Use the Alter Library Dialog Box>>.

4.  In the Alter Library dialog box, click the [ Browse ] button to
locate and select a new JAR file on the client workstation. The *Select
a code file* dialog box appears.

5.  In the *Select a code file* dialog box, locate and select the JAR
file on the client workstation, and click [ Open ] to return to the
Alter Library dialog box. The Alter Library dialog box displays the full
path of the new JAR file in the Code File field.

6.  Click [ Alter ] to alter the library, or click [ Close ] to quit the
dialog box without altering the library.
+
If you click [ Alter ], a dialog box appears warning you that altering a
library might affect stored procedures that use the library and asking
if you wish to continue the alter operation. Click [ Yes ] to proceed,
or click [ No ] to cancel the operation. If you click [ Yes ], HPDM
validates the JAR file, uploads the JAR file, and alters the library in
the schema.

7.  When notified that the library was altered successfully, click
[ OK ] to close the Alter Library dialog box and return to the HPDM main
window.

*Related Topics*

* <<use-the-alter-library-dialog-box, Use the Alter Library Dialog Box>>
* <<create-a-library, Create a Library>>
* <<drop-a-library, Drop a Library>>
* <<download-a-jar-file-from-a-library, Download a JAR File From a Library>>
* <<display-libraries-and-their-properties, Display Libraries and Their Properties>>

[[use-the-alter-library-dialog-box]]
== Use the Alter Library Dialog Box

The Alter Library dialog box allows you to alter a library and change
its underlying JAR file.

Requirements:

* You must have been granted the UPDATE privilege for the library. For
more information, see the Grant/Revoke Privileges Tool in HPDM or the
GRANT LIBRARY statement in the
http://trafodion.apache.org/docs/sql_reference/index.html#grant_statement[Trafodion SQL Reference Manual].

* You must either be the owner of the schema where you will alter the
library or have the ALTER_LIBRARY privilege for the schema to alter the
library. The schema owner can grant such a schema-level privilege to
other users or roles. For more information, see the Grant/Revoke
Privileges Tool in HPDM or the GRANT SCHEMA statement in the
http://trafodion.apache.org/docs/sql_reference/index.html#grant_statement[Trafodion SQL Reference Manual].

* The JAR file that you select for the library must contain valid Java
bytecode and must not be used by another library in the catalog.

* The JAR file that you select for the library must not exceed a size
threshold if one has been set for HPDM's internal WMS service, the data
source, or the system defaults.
+
For example, if the CONTROL QUERY DEFAULT (CQD) `POS_ABSOLUTE_MAX_TABLE_SIZE`
has been set for the HPS_MANAGEABILITY service, then it limits the size
of JAR files that can be uploaded by HPDM. If the JAR file's size
exceeds the threshold, a warning message is displayed, and the file is
not uploaded.
+
By default, this CQD is not set for HPDM's internal WMS
service, the data source, or the system defaults, and HPDM allows you to
upload JAR files of any size.


[cols="20%,30%,50%",options="header",]
|===
| Group Box   | Control or Field | Description or Action
| *Library*   | Catalog          | Name of the catalog where the library is created. This is a read-only field.
|             | Schema           | Name of the schema where the library is created. This is a read-only field.
|             | Library Name     | Name of the library. This is a read-only field.
| *Code File* | Code File        | Click [ Browse ] to launch the "Select a code file" dialog box and
navigate to a new JAR file on the client workstation.
|             | [ Alter ]        | Alters the library.
|             | [ Close ]        | Closes the dialog box without altering the library.
|             | [ Help ]         | Displays context-sensitive help for this dialog box.
|===

Related Topics

* <<alter-a-library, Alter a Library>>
* <<create-a-library, Create a Library>>
* <<drop-a-library, Drop a Library>>
* <<download-a-jar-file-from-a-library, Download a JAR File From a Library>>

[[drop-a-library]]
== Drop a Library

Dropping a library removes the library from the schema in the database
and removes the library's underlying JAR file from the Trafodion
database.

Requirements:

* You must either be the owner of the schema where you will drop the
library or have the DROP_LIBRARY privilege for the schema to drop the
library. The schema owner can grant such a schema-level privilege to
other users or roles. For more information, see the Grant/Revoke
Privileges Tool in HPDM or the GRANT SCHEMA statement in the
http://trafodion.apache.org/docs/sql_reference/index.html#grant_statement[Trafodion SQL Reference Manual].

To drop a library from the database:

1.  In HPDM, select the Database area.
2.  In the navigation tree pane, expand the tree to display the folders
of the schema that contains the library, and expand the Libraries folder
to display the libraries within it.
3.  Right-click the name of the library, and select Drop Library. The
Drop Library dialog box appears.
4.  In the Drop Library dialog box appears, select the Dropping all
procedures and routines using this library check box to drop all stored
procedures that are using the library. If you do not select this option
when stored procedures are using the library, the drop operation will
fail with an error message.
5.  Click [ Yes ] to drop the library, or click [ No ] to quit the
dialog box without dropping the library.

*Related Topics*

* <<create-a-library, Create a Library>>
* <<alter-a-library, Alter a Library>>
* <<download-a-jar-file-from-a-library, Download a JAR File From a Library>>
* <<display-libraries-and-their-properties, Display Libraries and Their Properties>>

[[download-a-jar-file-from-a-library]]
== Download a JAR File From a Library

Requirements:

* You must have the CREATE_LIBRARY privilege for the SQL_OPERATIONS
component. For more information, see the component privileges in the _HP
Database Manager (HPDM) User Guide_ or the online help in HPDM.

To download a JAR file from a library:

1.  In HPDM, select the Database area.

2.  In the navigation tree pane, expand the tree to display the folders
of the schema that contains the library, and expand the Libraries folder
to display the libraries within it.

3.  Right-click the name of the library, and select Browse Library. The
Browse Library dialog box appears with the name of the library selected
in the tree pane and displayed in the right pane. For more information,
see <<use-the-library-browser, Use the Library Browser>>.

4.  Click the [ Download ] button. The *Browse For Folder* dialog box
appears.

5.  In the *Browse For Folder* dialog box, select a target folder on the
client workstation for downloading the JAR file.

6.  Click [ OK ] to start downloading the library's underlying JAR file
to the client workstation, or click [ Cancel ] to quit the Browse For
Folder dialog box and return to the Browse Library dialog box.

7.  When notified that the download completed successfully, click [ OK ]
to return to the Browse Library dialog box.

*Related Topics*

* <<use-the-library-browser, Use the Library Browser>>
* <<create-a-library, Create a Library>>
* <<alter-a-library, Alter a Library>>
* <<drop-a-library, Drop a Library>>
* <<display-libraries-and-their-properties, Display Libraries and Their Properties>>

[[use-the-library-browser]]
== Use the Library Browser

Depending on the context in which the Library Browser is launched, you
can use it to view, create, or drop libraries in the database; to
download a JAR file from a library in the database to the client
workstation; or to select a Java method in a library when creating a
stored procedure.

[[display-libraries-and-their-properties]]
== Display Libraries and Their Properties

To display the libraries in a schema:

1.  Start the HP Database Manager and log on using any user name.
2.  Click the Database area.
3.  In the navigation tree pane, select a Schema, and expand the schema
so that you can see the object folders underneath it.
4.  Expand the Libraries tab in the right pane and select a library
name, or open the Libraries
folder and select a library name in the tree. HPDM displays the
libraries for this schema.

