////
/**
 *@@@ START COPYRIGHT @@@
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * @@@ END COPYRIGHT @@@
 */
////

[[install-odb]]
= Install odb

[[installation-requirements]]
== Installation Requirements

The odb tool runs on 64-bit Linux. On a Linux workstation, odb requires `pthread` libraries, which are usually installed by default. It also
requires the unixODBC Driver Manager to be installed and configured on the client workstation. For more information, see the
http://trafodion.apache.org/docs/odb_user/index.html[_Trafodion odb User Guide_].

[[installation-instructions]]
== Installation Instructions

NOTE: Before following these installation instructions, please make sure to install and configure unixODBC on the client workstation. For more
information, see the http://trafodion.apache.org/docs/odb_user/index.html[_Trafodion odb User Guide_].

You download and extract the Trafodion client package using the instructions in <<introduction-download, Download Installation Package>> above.

[[odb-install]]
=== Install odb

1.  Change the directory to the `clients` subdirectory.
2.  Unpack the contents of the `odb64_linux.tar.gz` file to a location on your client workstation:
+
```
mkdir $HOME/odb
tar -xzf odb64_linux.tar.gz -C $HOME/odb
```
+
The command extracts these files:
+
* `README`
* `/bin/odb64luo` (the odb executable)

3.  You are now ready to run the odb executable. For more information, see the http://trafodion.apache.org/docs/odb_user/index.html[_Trafodion odb User Guide_].

[[odb-uninstall]]
== Uninstall odb

To uninstall odb, delete the `README` and `/bin/odb64luo` files from their installed location.

```
rm -rf odb-installation-directory
```
