#######################################################################
# @@@ START COPYRIGHT @@@
#
# (C) Copyright 2007-2014 Hewlett-Packard Development Company, L.P.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
# @@@ END COPYRIGHT @@@
#######################################################################

CPPSRC := arkfs_dp2.cpp \
	ComVersionNodeInfo.cpp \
	ComVersionPublic.cpp \
	ieeemath.cpp \
	ExDp2Trace.cpp \
	stubs2.cpp  \
	vproceid.cpp \
	csconvert.cpp \
	ExDp2All1.cpp \
	ExDp2All2.cpp \
	ExDp2All3.cpp \
	ExDp2All4.cpp \
	ExDp2All5.cpp

  DEFS := -D__EID
  SRCPATH := arkfsindp2 common exp nskcre executor bin exeindp2

  EXTERN_OBJS += $(TOPDIR)/nskcre/ieeemath_asm.o
