////
/**
* @@@ START COPYRIGHT @@@
*
* Licensed to the Apache Software Foundation (ASF) under one
* or more contributor license agreements.  See the NOTICE file
* distributed with this work for additional information
* regarding copyright ownership.  The ASF licenses this file
* to you under the Apache License, Version 2.0 (the
* "License"); you may not use this file except in compliance
* with the License.  You may obtain a copy of the License at
*
*   http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing,
* software distributed under the License is distributed on an
* "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
* KIND, either express or implied.  See the License for the
* specific language governing permissions and limitations
* under the License.
*
* @@@ END COPYRIGHT @@@
  */
////

= About This Document
This guide describes how to install Trafodion for end-user environments. This install allows you to store and query data using Trafodion, either via Trafodion clients
(see http://trafodion.incubator.apache.org/client_install/index.html[Trafodion Client Installation Guide] or via application code you write.

If you want to install a Trafodion developer-build environment, then please refer to the 
http://trafodion.incubator.apache.org/contributor_guide/index.html[Trafodion Contributors' Guide].

== Intended Audience
This guide is intended for:

* *Single-Node Install*: Typically used when you want to evalulate Trafodion.
* *Cluster (Multi-Node) Install*: Typically used when you deploy Trafodion for application usage.

NOTE: Trafodion can be installed on a single-node or multi-node enviroment. Unless specifically noted, the term *cluster* is used
to mean both single- and multi-node environments.

The installation instructions applies to a diverse set of platforms:

* *Virtual Machines*: Often used for evaluations and Trafodion development.
* *Cloud*: Used for Product Environments as well as for Developer Environments.
* *Bare Metal*: Used for Product Environments as well as for Developer Environments.

NOTE: The term *node* is used to represent a computing platform on which operating system, Hadoop, and Trafodion software is running. 
Unless specifically qualified (bare-metal node, virtual-machin node, or cloud-node), *node* represents a computing platform in your cluster
regardless of platform type.

== New and Changed Information
This is a new guide.

== Notation Conventions
This list summarizes the notation conventions for syntax presentation in this manual.

[cols="15%,30%,25%,30%",options="header"]
|===
| Notation | Usage | Example | Notes
| UPPERCASE LETTERS | Uppercase letters indicate keywords and reserved words. Type these items exactly as shown. Items not enclosed in brackets are required. | SELECT | 
| _Italic Letters_ | Italic letters, regardless of font, indicate variable items that you supply. Items not enclosed in brackets are required. | _file-name_ | 
| `Computer Type` | Computer type letters within text indicate case-sensitive keywords and reserved words. Type these items exactly as shown. Items not enclosed in
brackets are required. | `myfile.sh` | 
| *Bold Text* | Bold text in an example indicates user input typed at the terminal. | `ENTER RUN CODE:` +
 ?**123** +
 `CODE RECEIVED: 123.00` | The user must press the Return key after typing the input.
| [ ] Brackets | Brackets enclose optional syntax items. |
DATETIME [__start-field__ TO] +
_end-field_
| A group of items enclosed in brackets is a list from which you can choose one item or none.

The items in the list can be arranged either vertically, with aligned brackets on each side of the list, or horizontally, enclosed in a pair of brackets and separated by vertical lines.

For example:

`DROP SCHEMA _schema_ [CASCADE]` +
`DROP SCHEMA _schema_ [ CASCADE \| RESTRICT ]`
| { } Braces | Braces enclose required syntax items. | `FROM { __grantee__[, __grantee__]...}` | A group of items enclosed in braces is a list from which you are required to choose one item.

The items in the list can be arranged either vertically, with aligned braces on each side of the list, or horizontally, enclosed in a pair of braces and separated by vertical lines.

For example:

`INTERVAL { _start-field_ TO _end-field_ }` +
`{ _single-field_ }` +
`INTERVAL { _start-field_ TO _end-field_ \| _single-field_ }` 
--
| \| Vertical Line | A vertical line separates alternatives in a horizontal list that is enclosed in brackets or braces. | `{__expression__ \| NULL}` |
| … Ellipsis | An ellipsis immediately following a pair of brackets or braces indicates that you can repeat the enclosed sequence of syntax items any number of times. |
`ATTRIBUTE[S] _attribute_ [, __attribute__]...` +
`{, __sql-expression__}...`
| An ellipsis immediately following a single syntax item indicates that you can repeat that syntax item any number of times.

For example:

`__expression-n__…`
| Punctuation | Parentheses, commas, semicolons, and other symbols not previously described must be typed as shown. |
DAY (__datetime-expression__)` +
`@__script-file__` | Quotation marks around a symbol such as a bracket or brace indicate the symbol is a required character that you must type as shown.

For example:

`"{" _module-name_ [, __module-name__]... "}"`
| Item Spacing | Spaces shown between items are required unless one of the items is a punctuation symbol such as a parenthesis or a comma. |
`DAY (__datetime-expression__) DAY(__datetime-expression__)` | If there is no space between two items, spaces are not permitted. In this example, no spaces are permitted between the period and any other items:

`__myfile__.sh`

| Line Spacing | If the syntax of a command is too long to fit on a single line, each continuation line is indented three spaces and is separated from the preceding line by a blank line.

This spacing distinguishes items in a continuation line from items in a vertical list of selections. | 
`_match-value_ [NOT] LIKE _pattern_`
   [ESCAPE __esc-char-expression__] |
|===

== Publishing History
[cols="2*",options="header"]
|===
| Product Version | Publication Date
| Trafodion Release 1.3.0 | To be announced.
|===

== Comments Encouraged
The Trafodion community encourages your comments concerning this document. We are committed to providing documentation that meets your
needs. Send any errors found, suggestions for improvement, or compliments to:

issues@trafodion.incubator.apache.org

Include the document title and any comment, error found, or suggestion for improvement you have concerning this document.

