#!/bin/bash
# @@@ START COPYRIGHT @@@
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# @@@ END COPYRIGHT @@@

#This script will uninstall MapR

#==============================================
#Stop the Warden on all nodes
service mapr-warden stop

#Stop ZooKeeper on all nodes
service mapr-zookeeper stop

#Delete all mapr-core* files
sudo yum --assumeyes erase mapr-core\*

#Delete all mapr-zk-internal* files
sudo yum --assumeyes erase mapr-zk-internal\*

#Delete /opt/mapr directory and all files within
sudo rm -rf /opt/mapr

#Delete /opt/storagefile and /opt/mapr-setup
sudo rm -rf /opt/storagefile
sudo rm -rf /opt/mapr-setup

#Delete any cached repos
sudo rm -rf /var/cache/yum/x86_64/6/mapr*
sudo yum clean all

#==============================================
