#!/bin/bash
# @@@ START COPYRIGHT @@@
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# @@@ END COPYRIGHT @@@

export TRAF_CONFIG=/etc/trafodion/trafodion_config

source $TRAF_CONFIG

STARTING_NODE=$(hostname)

#==========================================
echo "***INFO: starting sqgen" | tee -a $INSTALL_LOG
cd $TRAF_HOME/sql/scripts

#If sqconfig.db exists remove it and then sqgen can be run
if [[ -e $TRAF_HOME/sql/scripts/sqconfig.db ]]; then
   $TRAF_PDSH rm -rf $TRAF_HOME/sql/scripts/sqconfig.db
fi

$TRAF_HOME/sql/scripts/sqgen
SQGEN_RC=$?
if [ "$SQGEN_RC" != "0" ]; then
    echo "***ERROR: sqgen failed with RC=$SQGEN_RC. Check install log file for details." | tee -a $INSTALL_LOG
    exit -1;
fi
#==========================================

if [ "$node_count" -ne "1" ]; then
    echo "***INFO: copying $HOME/sqcert directory to all nodes" | tee -a $INSTALL_LOG
    $PDCP $ALL_NODES -x $HOSTNAME -r $HOME/sqcert $HOME
fi


#==========================================

if [ "$all_node_count" -ne "1" ]; then
   
   echo "***INFO: copying install to all nodes" | tee -a $INSTALL_LOG
   $PDCP $ALL_NODES -x $HOSTNAME -r $TRAF_HOME $TRAF_HOME/..

   if [ "$?" != "0" ]; then
      echo "***ERROR: Unable to copy Trafodion install to all machines in this cluster.  Check install log files for details." | tee -a $INSTALL_LOG
      exit -1;
   fi
fi

#=========================================
#Copying certificate to scripts directory
if [[ "$LDAP_SECURITY" == "Y" ]]; then
   if [[ $LDAP_LEVEL == "1" ]]; then
      echo "TLS_CACERT $HOME/$LDAP_CERT_BASE" > $HOME_DIR/$TRAF_USER/.ldaprc
      echo "TLS_REQCERT demand" >> $HOME_DIR/$TRAF_USER/.ldaprc
   fi
fi

#==========================================

