#######################################################################
# @@@ START COPYRIGHT @@@
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# @@@ END COPYRIGHT @@@
#######################################################################

CPPSRC := \
	BaseTypes.cpp \
	BigNumHelper.cpp \
	charinfo.cpp \
	CharType.cpp \
	ColIndList.cpp \
	ComAnsiNamePart.cpp \
	ComRoutineActionNamePart.cpp \
	ComDistribution.cpp \
	ComExeTrace.cpp \
	ComExtents.cpp \
	ComGuardianFileNameParts.cpp \
	ComJSON.cpp \
	ComJSONFuncs.cpp \
	ComJSONStringInfo.cpp \
	ComLocationNames.cpp \
	ComMisc.cpp \
	ComMPLoc.cpp \
	ComMvAttributeBitmap.cpp \
	ComObjectName.cpp \
	ComplexObject.cpp \
	ComRegAPI.cpp \
	ComResWords.cpp \
	ComRtUtils.cpp \
	ComSafePrinter.cpp \
	ComSchemaName.cpp \
	ComSmallDefs.cpp \
	ComSpace.cpp \
	ComSqlId.cpp \
	ComSqlText.cpp \
	ComSSL.cpp \
	ComSysUtils.cpp \
	ComTransInfo.cpp \
	conversionISO88591.cpp \
	conversionLocale.cpp \
	conversionSJIS.cpp \
	conversionKSC5601.cpp \
	conversionHex.cpp \
	csconvert.cpp \
	DateTimeType.cpp \
	DgBaseType.cpp \
	DTICommonType.cpp \
	ErrorCondition.cpp \
	ExprNode.cpp \
	Int64.cpp \
	IntervalType.cpp \
	Ipc.cpp \
	IpcGuardian.cpp \
	IpcSockets.cpp \
	MiscType.cpp \
	NAAssert.cpp \
	NAError.cpp \
	NAIpc.cpp \
	NALog.cpp \
	NAMemory.cpp \
	NAStdioFile.cpp \
	NAString.cpp \
	NAString2.cpp \
	NATestpoint.cpp \
	NAType.cpp \
        ComUser.cpp \
	ComSecurityKey.cpp \
	NLSConversion.cpp \
	NumericType.cpp \
	SequenceGeneratorAttributes.cpp \
	str.cpp \
	stringBuf.cpp  \
	TempIncludes.cpp \
	unicode_char_set.cpp \
	wstr.cpp \
	BloomFilter.cpp \
	VarInt.cpp 

CPPSRC += ComCextMisc.cpp

SRCPATH := common porting_layer 

CPPSRC += PortProcessCalls.cpp vers_libcommon.cpp
CPPSRC += SMConnection.cpp
