// @@@ START COPYRIGHT @@@
//
// (C) Copyright 2015 Hewlett-Packard Development Company, L.P.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
// @@@ END COPYRIGHT @@@
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: common.qpid_header.proto
namespace common
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"qpid_header")]
  public partial class qpid_header : global::ProtoBuf.IExtensible
  {
    public qpid_header() {}
    
    private long _generation_time_ts_utc;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"generation_time_ts_utc", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long generation_time_ts_utc
    {
      get { return _generation_time_ts_utc; }
      set { _generation_time_ts_utc = value; }
    }
    private long _generation_time_ts_lct;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"generation_time_ts_lct", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long generation_time_ts_lct
    {
      get { return _generation_time_ts_lct; }
      set { _generation_time_ts_lct = value; }
    }
    private uint _version;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint version
    {
      get { return _version; }
      set { _version = value; }
    }
    private uint _cluster_id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"cluster_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint cluster_id
    {
      get { return _cluster_id; }
      set { _cluster_id = value; }
    }
    private uint _domain_id;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"domain_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint domain_id
    {
      get { return _domain_id; }
      set { _domain_id = value; }
    }
    private uint _subdomain_id;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"subdomain_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint subdomain_id
    {
      get { return _subdomain_id; }
      set { _subdomain_id = value; }
    }
    private uint _instance_id;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"instance_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint instance_id
    {
      get { return _instance_id; }
      set { _instance_id = value; }
    }
    private uint _tenant_id;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"tenant_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint tenant_id
    {
      get { return _tenant_id; }
      set { _tenant_id = value; }
    }
    private uint _component_id;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"component_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint component_id
    {
      get { return _component_id; }
      set { _component_id = value; }
    }
    private int _process_id;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"process_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int process_id
    {
      get { return _process_id; }
      set { _process_id = value; }
    }
    private uint _thread_id;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"thread_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint thread_id
    {
      get { return _thread_id; }
      set { _thread_id = value; }
    }

    private uint _node_id = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"node_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint node_id
    {
      get { return _node_id; }
      set { _node_id = value; }
    }

    private uint _pnid_id = default(uint);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"pnid_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint pnid_id
    {
      get { return _pnid_id; }
      set { _pnid_id = value; }
    }
    private string _ip_address_id;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"ip_address_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ip_address_id
    {
      get { return _ip_address_id; }
      set { _ip_address_id = value; }
    }
    private uint _sequence_num;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"sequence_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint sequence_num
    {
      get { return _sequence_num; }
      set { _sequence_num = value; }
    }

    private string _process_name = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"process_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string process_name
    {
      get { return _process_name; }
      set { _process_name = value; }
    }
    private uint _host_id;
    [global::ProtoBuf.ProtoMember(17, IsRequired = true, Name=@"host_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint host_id
    {
      get { return _host_id; }
      set { _host_id = value; }
    }

    private string _system_version = "";
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"system_version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string system_version
    {
      get { return _system_version; }
      set { _system_version = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
