// @@@ START COPYRIGHT @@@
//
// (C) Copyright 2015 Hewlett-Packard Development Company, L.P.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
// @@@ END COPYRIGHT @@@
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: common.health_template.proto
// Note: requires additional types generated from: common.health_header.proto
namespace health
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"health_template")]
  public partial class health_template : global::ProtoBuf.IExtensible
  {
    public health_template() {}
    
    private common.health_header _header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public common.health_header header
    {
      get { return _header; }
      set { _header = value; }
    }
    private readonly global::System.Collections.Generic.List<health.health_template.health_template_data_struct> _data = new global::System.Collections.Generic.List<health.health_template.health_template_data_struct>();
    [global::ProtoBuf.ProtoMember(2, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<health.health_template.health_template_data_struct> data
    {
      get { return _data; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"health_template_data_struct")]
  public partial class health_template_data_struct : global::ProtoBuf.IExtensible
  {
    public health_template_data_struct() {}
    
    private int _logical_object_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"logical_object_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int logical_object_type
    {
      get { return _logical_object_type; }
      set { _logical_object_type = value; }
    }

    private int _logical_object_subtype = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"logical_object_subtype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int logical_object_subtype
    {
      get { return _logical_object_subtype; }
      set { _logical_object_subtype = value; }
    }
    private string _logical_object_name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"logical_object_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string logical_object_name
    {
      get { return _logical_object_name; }
      set { _logical_object_name = value; }
    }

    private string _logical_object_qual_1 = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"logical_object_qual_1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string logical_object_qual_1
    {
      get { return _logical_object_qual_1; }
      set { _logical_object_qual_1 = value; }
    }

    private string _logical_object_qual_2 = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"logical_object_qual_2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string logical_object_qual_2
    {
      get { return _logical_object_qual_2; }
      set { _logical_object_qual_2 = value; }
    }

    private string _logical_object_path = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"logical_object_path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string logical_object_path
    {
      get { return _logical_object_path; }
      set { _logical_object_path = value; }
    }

    private int _physical_object_type = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"physical_object_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int physical_object_type
    {
      get { return _physical_object_type; }
      set { _physical_object_type = value; }
    }

    private int _physical_object_subtype = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"physical_object_subtype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int physical_object_subtype
    {
      get { return _physical_object_subtype; }
      set { _physical_object_subtype = value; }
    }

    private string _physical_object_name = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"physical_object_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string physical_object_name
    {
      get { return _physical_object_name; }
      set { _physical_object_name = value; }
    }

    private int _current_state = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"current_state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int current_state
    {
      get { return _current_state; }
      set { _current_state = value; }
    }

    private string _current_state_raw = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"current_state_raw", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string current_state_raw
    {
      get { return _current_state_raw; }
      set { _current_state_raw = value; }
    }

    private int _previous_state = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"previous_state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int previous_state
    {
      get { return _previous_state; }
      set { _previous_state = value; }
    }

    private string _previous_state_raw = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"previous_state_raw", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string previous_state_raw
    {
      get { return _previous_state_raw; }
      set { _previous_state_raw = value; }
    }

    private long _state_change_ts_lct = default(long);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"state_change_ts_lct", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long state_change_ts_lct
    {
      get { return _state_change_ts_lct; }
      set { _state_change_ts_lct = value; }
    }

    private long _state_change_ts_utc = default(long);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"state_change_ts_utc", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long state_change_ts_utc
    {
      get { return _state_change_ts_utc; }
      set { _state_change_ts_utc = value; }
    }

    private int _current_health = default(int);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"current_health", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int current_health
    {
      get { return _current_health; }
      set { _current_health = value; }
    }

    private string _current_health_raw = "";
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"current_health_raw", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string current_health_raw
    {
      get { return _current_health_raw; }
      set { _current_health_raw = value; }
    }

    private int _previous_health = default(int);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"previous_health", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int previous_health
    {
      get { return _previous_health; }
      set { _previous_health = value; }
    }

    private string _previous_health_raw = "";
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"previous_health_raw", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string previous_health_raw
    {
      get { return _previous_health_raw; }
      set { _previous_health_raw = value; }
    }

    private long _health_change_ts_lct = default(long);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"health_change_ts_lct", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long health_change_ts_lct
    {
      get { return _health_change_ts_lct; }
      set { _health_change_ts_lct = value; }
    }

    private long _health_change_ts_utc = default(long);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"health_change_ts_utc", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long health_change_ts_utc
    {
      get { return _health_change_ts_utc; }
      set { _health_change_ts_utc = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
