// @@@ START COPYRIGHT @@@
//
// (C) Copyright 2015 Hewlett-Packard Development Company, L.P.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
// @@@ END COPYRIGHT @@@
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: health.layer_check.proto
// Note: requires additional types generated from: common.health_header.proto
namespace health
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"layer_check")]
  public partial class layer_check : global::ProtoBuf.IExtensible
  {
    public layer_check() {}
    
    private common.health_header _header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public common.health_header header
    {
      get { return _header; }
      set { _header = value; }
    }
    private string _layer_name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"layer_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string layer_name
    {
      get { return _layer_name; }
      set { _layer_name = value; }
    }

    private int _layer_current_score = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"layer_current_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int layer_current_score
    {
      get { return _layer_current_score; }
      set { _layer_current_score = value; }
    }

    private int _layer_previous_score = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"layer_previous_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int layer_previous_score
    {
      get { return _layer_previous_score; }
      set { _layer_previous_score = value; }
    }

    private long _layer_score_change_ts_lct = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"layer_score_change_ts_lct", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long layer_score_change_ts_lct
    {
      get { return _layer_score_change_ts_lct; }
      set { _layer_score_change_ts_lct = value; }
    }

    private long _layer_score_change_ts_utc = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"layer_score_change_ts_utc", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long layer_score_change_ts_utc
    {
      get { return _layer_score_change_ts_utc; }
      set { _layer_score_change_ts_utc = value; }
    }
    private readonly global::System.Collections.Generic.List<health.layer_check.health_layer_data_struct> _data = new global::System.Collections.Generic.List<health.layer_check.health_layer_data_struct>();
    [global::ProtoBuf.ProtoMember(7, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<health.layer_check.health_layer_data_struct> data
    {
      get { return _data; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"health_layer_data_struct")]
  public partial class health_layer_data_struct : global::ProtoBuf.IExtensible
  {
    public health_layer_data_struct() {}
    
    private string _subject_name;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"subject_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string subject_name
    {
      get { return _subject_name; }
      set { _subject_name = value; }
    }

    private int _subject_current_score = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"subject_current_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int subject_current_score
    {
      get { return _subject_current_score; }
      set { _subject_current_score = value; }
    }

    private int _subject_previous_score = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"subject_previous_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int subject_previous_score
    {
      get { return _subject_previous_score; }
      set { _subject_previous_score = value; }
    }

    private long _subject_score_change_ts_lct = default(long);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"subject_score_change_ts_lct", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long subject_score_change_ts_lct
    {
      get { return _subject_score_change_ts_lct; }
      set { _subject_score_change_ts_lct = value; }
    }

    private long _subject_score_change_ts_utc = default(long);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"subject_score_change_ts_utc", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long subject_score_change_ts_utc
    {
      get { return _subject_score_change_ts_utc; }
      set { _subject_score_change_ts_utc = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
