// @@@ START COPYRIGHT @@@
//
// (C) Copyright 2015 Hewlett-Packard Development Company, L.P.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
// @@@ END COPYRIGHT @@@
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: linuxcounters.filesystem_metrics_shortbusy_assembled.proto
// Note: requires additional types generated from: common.info_header.proto
namespace linuxcounters
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"filesystem_metrics_shortbusy_assembled")]
  public partial class filesystem_metrics_shortbusy_assembled : global::ProtoBuf.IExtensible
  {
    public filesystem_metrics_shortbusy_assembled() {}
    
    private common.info_header _header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public common.info_header header
    {
      get { return _header; }
      set { _header = value; }
    }
    private readonly global::System.Collections.Generic.List<linuxcounters.filesystem_metrics_shortbusy_assembled.aggregate_filesystem_count> _filesystem_count_aggr = new global::System.Collections.Generic.List<linuxcounters.filesystem_metrics_shortbusy_assembled.aggregate_filesystem_count>();
    [global::ProtoBuf.ProtoMember(2, Name=@"filesystem_count_aggr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<linuxcounters.filesystem_metrics_shortbusy_assembled.aggregate_filesystem_count> filesystem_count_aggr
    {
      get { return _filesystem_count_aggr; }
    }
  
    private readonly global::System.Collections.Generic.List<linuxcounters.filesystem_metrics_shortbusy_assembled.aggregate_filesystem_use_buffer> _aggregate = new global::System.Collections.Generic.List<linuxcounters.filesystem_metrics_shortbusy_assembled.aggregate_filesystem_use_buffer>();
    [global::ProtoBuf.ProtoMember(3, Name=@"aggregate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<linuxcounters.filesystem_metrics_shortbusy_assembled.aggregate_filesystem_use_buffer> aggregate
    {
      get { return _aggregate; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"aggregate_filesystem_use_buffer")]
  public partial class aggregate_filesystem_use_buffer : global::ProtoBuf.IExtensible
  {
    public aggregate_filesystem_use_buffer() {}
    
    private int _node_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"node_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int node_id
    {
      get { return _node_id; }
      set { _node_id = value; }
    }
    private string _mnt_fsname;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mnt_fsname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mnt_fsname
    {
      get { return _mnt_fsname; }
      set { _mnt_fsname = value; }
    }
    private string _mnt_dir;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"mnt_dir", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mnt_dir
    {
      get { return _mnt_dir; }
      set { _mnt_dir = value; }
    }
    private int _percent_consumed;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"percent_consumed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int percent_consumed
    {
      get { return _percent_consumed; }
      set { _percent_consumed = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"aggregate_filesystem_count")]
  public partial class aggregate_filesystem_count : global::ProtoBuf.IExtensible
  {
    public aggregate_filesystem_count() {}
    
    private int _num_file_systems;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"num_file_systems", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num_file_systems
    {
      get { return _num_file_systems; }
      set { _num_file_systems = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
