/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_trafodion_sql_HBaseAccess_HTableClient */

#ifndef _Included_org_trafodion_sql_HBaseAccess_HTableClient
#define _Included_org_trafodion_sql_HBaseAccess_HTableClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_trafodion_sql_HBaseAccess_HTableClient
 * Method:    setResultInfo
 * Signature: (J[I[I[I[I[I[I[J[[B[[B[II)I
 */
JNIEXPORT jint JNICALL Java_org_trafodion_sql_HBaseAccess_HTableClient_setResultInfo
  (JNIEnv *, jobject, jlong, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jlongArray, jobjectArray, jobjectArray, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_trafodion_sql_HBaseAccess_HTableClient_QualifiedColumn */

#ifndef _Included_org_trafodion_sql_HBaseAccess_HTableClient_QualifiedColumn
#define _Included_org_trafodion_sql_HBaseAccess_HTableClient_QualifiedColumn
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
