/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_trafodion_sql_HBaseAccess_HTableClient */

#ifndef _Included_org_trafodion_sql_HBaseAccess_HTableClient
#define _Included_org_trafodion_sql_HBaseAccess_HTableClient
#ifdef __cplusplus
extern "C" {
#endif
#undef org_trafodion_sql_HBaseAccess_HTableClient_GET_ROW
#define org_trafodion_sql_HBaseAccess_HTableClient_GET_ROW 1L
#undef org_trafodion_sql_HBaseAccess_HTableClient_BATCH_GET
#define org_trafodion_sql_HBaseAccess_HTableClient_BATCH_GET 2L
#undef org_trafodion_sql_HBaseAccess_HTableClient_SCAN_FETCH
#define org_trafodion_sql_HBaseAccess_HTableClient_SCAN_FETCH 3L
/*
 * Class:     org_trafodion_sql_HBaseAccess_HTableClient
 * Method:    setResultInfo
 * Signature: (J[I[I[I[I[I[I[J[[B[[B[II)I
 */
JNIEXPORT jint JNICALL Java_org_trafodion_sql_HBaseAccess_HTableClient_setResultInfo
  (JNIEnv *, jobject, jlong, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jlongArray, jobjectArray, jobjectArray, jintArray, jint);

/*
 * Class:     org_trafodion_sql_HBaseAccess_HTableClient
 * Method:    cleanup
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_trafodion_sql_HBaseAccess_HTableClient_cleanup
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_trafodion_sql_HBaseAccess_HTableClient
 * Method:    setJavaObject
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_trafodion_sql_HBaseAccess_HTableClient_setJavaObject
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_trafodion_sql_HBaseAccess_HTableClient_ScanHelper */

#ifndef _Included_org_trafodion_sql_HBaseAccess_HTableClient_ScanHelper
#define _Included_org_trafodion_sql_HBaseAccess_HTableClient_ScanHelper
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_trafodion_sql_HBaseAccess_HTableClient_SnapshotScanHelper */

#ifndef _Included_org_trafodion_sql_HBaseAccess_HTableClient_SnapshotScanHelper
#define _Included_org_trafodion_sql_HBaseAccess_HTableClient_SnapshotScanHelper
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
