.TH CKILL 1 "05 May 2010" "SQ scripts" "SQ-SCRIPTS Reference Pages"
.SH NAME
ckill \- cluster process kill
.LP
.SH SYNOPSIS
.B ckill
program
\&.\.\.
.SH DESCRIPTION
.LP
.B ckill
will send a SIGKILL to all processes matching program
over all nodes in a cluster.
.B ckill
will work like traf_pkill if the host is not a cluster-system.
.SH SEE ALSO
.I kill.
