.TH SQTRACE 1 "05 May 2010" "SQ scripts" "SQ-SCRIPTS Reference Pages"
.SH NAME
sqtrace \- start/stop seabed-trace
.LP
.SH SYNOPSIS
.B sqtrace
<process-name> <0|1>
.SH DESCRIPTION
.LP
.B sqtrace
will start or stop the seabed-tracing of the specified SQ process.
.SH Example
sqtrace \\$DATA01 1
.LP
Starts the seabed-trace of $DATA.
.SH SEE ALSO
.I shell.
