.TH SQVERS 1 "05 March 2013" "SQ bin" "SQ-BIN Reference Pages"
.SH NAME
sqvers \- Display SQ version information
.LP
.SH SYNOPSIS
.B sqvers
[
.B -d
]
[
.B -h
]
[
.B -u
]
[
.B -v
]
.SH DESCRIPTION
.LP
.B sqvers
will display SQ version information.
.SH USAGE
.TP 10
.BI -d
Display detail (used with -u).
.br
Normally, -u will not display files with most common version.
.TP
.BI -h
Display help.
.TP
.BI -u
Display UTTs.
.TP
.BI -v
Verbose output (debug usage).
.SH SEE ALSO
.I file.
.I hostname.
.I java.
.I nm.
.I whoami.
.SH FILES
$MY_SQROOT/export/bin64/*
.br
$MY_SQROOT/export/lib/*
.br
$MY_SQROOT/export/lib64/*
.br
$MY_SQROOT/opt/hpmpi/lib/linux_amd64/*
