.TH WMSSTART 1 "05 May 2010" "SQ scripts" "SQ-SCRIPTS Reference Pages"
.SH NAME
wmsstart \- WMS start
.LP
.SH SYNOPSIS
.B wmsstart
[
.B \-s |
.B \-q |
.B \-h |

.SH DESCRIPTION
.LP
.B wmsstart
will start the WMS environment.
WMS must be stopped before it can be started.
.B wmsstart
will return an exit code of 0 if successful, or a non zero exit code otherwise.
.SH USAGE
.TP 7
.BI -s
Starts QSSYNC as non-persistent process.
.TP
.BI -q 
will suppress all output text.
.TP
.BI -h
will display help.
.SH SEE ALSO
.I shell.
