.TH WMSSTOP 1 "05 May 2010" "SQ scripts" "SQ-SCRIPTS Reference Pages"
.SH NAME
wmsstop \- WMS stop
.LP
.SH SYNOPSIS
.B wmsstop
[
.B -q |
.B -h
]
.SH DESCRIPTION
.LP
.B wmsstop
will stop the WMS environment.
.B wmstop
will return an exit code of 0 if successful, or a non zero exit code otherwise.
.SH USAGE
.TP 10
.BI -q
Suppresses all output text.
.TP
.BI -h
will display help.
.SH SEE ALSO
.I shell.
