.\" @@@ START COPYRIGHT @@@
.\"
.\" Licensed to the Apache Software Foundation (ASF) under one
.\" or more contributor license agreements.  See the NOTICE file
.\" distributed with this work for additional information
.\" regarding copyright ownership.  The ASF licenses this file
.\" to you under the Apache License, Version 2.0 (the
.\" "License"); you may not use this file except in compliance
.\" with the License.  You may obtain a copy of the License at
.\"
.\"   http://www.apache.org/licenses/LICENSE-2.0
.\"
.\" Unless required by applicable law or agreed to in writing,
.\" software distributed under the License is distributed on an
.\" "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
.\" KIND, either express or implied.  See the License for the
.\" specific language governing permissions and limitations
.\" under the License.
.\"
.\" @@@ END COPYRIGHT @@@
.\"
.\"#############################################################
.TH SQ 1 "05 March 2013" "SQ" "SQ Reference Pages"
.SH LIST OF COMMANDS
.nf
.sp
.ta 22n +20n
\fBName 	Appears on Page 	Description\fR
.sp
.zZ
\fBckill\fP	\fBckill\fP(1)	Cluster kill
\fBckillall\fP	\fBckillall\fP(1)	Cluster killall
\fBclean\fP	\fBclean\fP(1)	Clean trace/core/temp files
\fBcleanat\fP	\fBcleanat\fP(1)	Clean audit-trail files
\fBcleandb\fP	\fBcleandb\fP(1)	Clean database
\fBcreatehooks\fP	\fBcreatehooks\fP(1)	Create hook files
\fBcreatesysmdf\fP	\fBcreatesysmdf\fP(1)	Create SQL System Module Files
\fBcstat\fP	\fBcstat\fP(1)	Cluster process status
\fBdbsize\fP	\fBdbsize\fP(1)	Database size
\fBdelhooks\fP	\fBdelhooks\fP(1)	Delete hook files
\fBerror\fP	\fBerror\fP(1)	Display Guardian-error message
\fBinit_sql\fP	\fBinit_sql\fP(1)	Initialize SQL
\fBmed\fP	\fBmed\fP(1)	MPI-error decode
\fBndcsbind\fP	\fBndcsbind\fP(1) 	NDCS bind
\fBndcscheck\fP	\fBndcscheck\fP(1) 	Check the NDCS environment
\fBndcsstart\fP	\fBndcsstart\fP(1) 	Start the NDCS environment
\fBndcsstop\fP	\fBndcsstop\fP(1) 	Stop the NDCS environment
\fBpkillall\fP	\fBpkillall\fP(1)	Process killall
\fBpstacksq\fP	\fBpstacksq\fP(1)	pstack with line numbers
\fBpstat\fP	\fBpstat\fP(1)	Process status (SQL processes)
\fBsbcalc\fP	\fBsbcalc\fP(1)	SB Calculator
\fBsbop\fP	\fBsbop\fP(1)	SB profiler op extractor
\fBsbopd\fP	\fBsbopd\fP(1)	SB profiler op detail extractor
\fBseabedinfo\fP	\fBseabedinfo\fP(1)	SB info
\fBshell\fP	\fBshell\fP(1)	Monitor shell
\fBsqcheck\fP	\fBsqcheck\fP(1)	Checks status of the SQ env
\fBsqcheckmon\fP	\fBsqcheckmon\fP(1)	Checks status of the SQ monitor
\fBsqcore\fP	\fBsqcore\fP(1)	Collects core-files
\fBsqcorefile\fP	\fBsqcorefile\fP(1)	Display core-file information
\fBsqdbseedcreate\fP	\fBsqdbseedcreate\fP(1)	Create sq-db-seed-disk
\fBsqdbseedinstall\fP	\fBsqdbseedinstall\fP(1)	Install sq-db-seed-disk
\fBsqgen\fP	\fBsqgen\fP(1)	Script generator
\fBsqgetfiles\fP	\fBsqgetfiles\fP(1)	Creates SQL file list per disk	
\fBsqhc\fP	\fBsqhc\fP(1)	Health check
\fBsqid\fP	\fBsqid\fP(1)	Display SQ identifier
\fBsqinfo\fP	\fBsqinfo\fP(1)	Collect SQ information
\fBsqipcrm\fP	\fBsqipcrm\fP(1)	Ipcrm (clean shr mem/sem/q)
\fBsqkill\fP	\fBsqkill\fP(1)	Kill through shell
\fBsqps\fP	\fBsqps\fP(1)	Ps through shell
\fBsqpstack\fP	\fBsqpstack\fP(1)	Pstack for SQ program
\fBsqshell\fP	\fBsqshell\fP(1)	Shell (SQ)
\fBsqsk\fP	\fBsqsk\fP(1)	Search & kill through shell
\fBsqstart\fP	\fBsqstart\fP(1)	Start system
\fBsqstate\fP	\fBsqstate\fP(1)	Display SQ state
\fBsqstop\fP	\fBsqstop\fP(1)	Stop system
\fBsqtrace\fP	\fBsqtrace\fP(1)	Turn on/off SB dynamic-trace
\fBsqvers\fP	\fBsqvers\fP(1)	Display SQ version information
\fBtcorestr\fP	\fBtcorestr\fP(1)	Search for string in core-file
\fBtdelta\fP	\fBtdelta\fP(1)	Print trace delta
\fBtmerge\fP	\fBtmerge\fP(1)	Trace merge
\fBtprogress\fP	\fBtprogress\fP(1)	Measure copy progress
\fBtraf_pkill\fP	\fBtraf_pkill\fP(1)	Process kill
\fBtsearch\fP	\fBtsearch\fP(1)	Search for string
\fBupdate_sql\fP	\fBupdate_sql\fP(1)	Update SQL
\fBwmscheck\fP	\fBwmscheck\fP(1) 	Check the WMS environment
\fBwmsstart\fP	\fBwmsstart\fP(1) 	Start the WMS environment
\fBwmsstop\fP	\fBwmsstop\fP(1) 	Stop the WMS environment
.fi
