.TH SQCHECKMON 1 "04 October 2012" "SQ scripts" "SQ-SCRIPTS Reference Pages"
.SH NAME
sqcheckmon \- Checks the health of the SQ monitor
.LP
.SH SYNOPSIS
.B sqcheckmon
.SH DESCRIPTION
.LP
.B sqcheckmon
will try to connect to the SQ monitor on the current node and prints the result of the operation.
.B sqcheckmon
returns an exit code of 0 if successful, and 1 otherwise.
.SH Log File
Logs its output in the file sqcheckmon.log of the current directory

