.\" @@@ START COPYRIGHT @@@
.\"
.\" Licensed to the Apache Software Foundation (ASF) under one
.\" or more contributor license agreements.  See the NOTICE file
.\" distributed with this work for additional information
.\" regarding copyright ownership.  The ASF licenses this file
.\" to you under the Apache License, Version 2.0 (the
.\" "License"); you may not use this file except in compliance
.\" with the License.  You may obtain a copy of the License at
.\"
.\"   http://www.apache.org/licenses/LICENSE-2.0
.\"
.\" Unless required by applicable law or agreed to in writing,
.\" software distributed under the License is distributed on an
.\" "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
.\" KIND, either express or implied.  See the License for the
.\" specific language governing permissions and limitations
.\" under the License.
.\"
.\" @@@ END COPYRIGHT @@@
.\"
.\"#############################################################
.TH SQINFO 1 "05 October 2012" "SQ bin" "SQ-BIN Reference Pages"
.SH NAME
sqinfo \- Collects SQ information
.LP
.SH SYNOPSIS
.B sqinfo
[
.B -d
]
.SH DESCRIPTION
.LP
.B sqinfo
will collect SQ information.
By default, a 'brief' collection is used.
.SH USAGE
.TP 7
.BI -d
will display detailed SQ information.
.SH SEE ALSO
.I env.
.I hostname.
.I ifconfig.
.I mpirun.
.I nm.
.I pdsh.
.I sqid.
.I sqvers.
.I uname.
.I which.
.SH FILES
/etc/hosts
.br
/etc/*release
.br
/etc/security/limits.conf
.br
/proc/meminfo
.br
/proc/net/dev
.br
$TRAF_VAR/ms.env
.br
$TRAF_VAR/mon.env
.br
$TRAF_VAR/shell.env
.br
$TRAF_CONF/sqconfig
