.TH SQSTOP 1 "05 May 2010" "SQ scripts" "SQ-SCRIPTS Reference Pages"
.SH NAME
sqstop \- SQ stop
.LP
.SH SYNOPSIS
.B sqstop
[
.B abrupt |
.B immediate
]
.SH DESCRIPTION
.LP
.B sqstop
will stop SQ system.
With no parameters,
.B sqstop
will do a normal system stop.
.SH USAGE
.TP 10
.BI abrupt
will do an abrupt system stop.
.TP
.BI immediate
will do an immediate system stop.
.SH SEE ALSO
.I shell.
