#!/bin/bash
# @@@ START COPYRIGHT @@@ 
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
# @@@ END COPYRIGHT @@@

dcsznode=/$USER/dcs/master
dcstmp=/tmp/dcstmp-$USER.log

if [ -d $DCS_INSTALL_DIR ];then
   echo "ls $dcsznode"|$DCS_INSTALL_DIR/bin/dcs zkcli > $dcstmp
   zkport=`cat $dcstmp | /usr/bin/head -n 1 | cut -d ":" -f2`
   if [ ! -z "$zkport" ]; then
     echo "Zookeeper is listening on port $zkport"
   else
     echo "Zookeeper is not started..."
     exit 1
   fi
   masterport=`cat $dcstmp | /usr/bin/tail -n 1 | cut -d ":" -f4`
   if [ ! -z "$masterport" ]; then
     echo "Dcs Master is listening on port $masterport"
   else
     echo "Dcs Master is not started ..."
     exit 1
   fi
   rm -f $dcstmp
else
   echo "DCS is not installed..."
   exit 1
fi
