#!/bin/bash
# @@@ START COPYRIGHT @@@
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# @@@ END COPYRIGHT @@@

xcli=t83fs
xmid=t83fs
xsrv=t83fs

# setup
. ./gosetup

echo "********* TEST `date` t83 - $xcli/$xmid/$xsrv *********"
tcheck -setup
. ./goshellsetup
cat > $TMP <<eof
node
! Start the monitor processes across the cluster
startup
! Start the test server
exec {nowait,name \$SRV} $xsrv -server $*
exec {nowait,name \$MID} $xmid -mid $*
! Display process status of our processes
ps
! Start the client process
exec {$nid0 name \$CLI} $xcli -client $*
! Display process status to see new processes
ps
! Wait for our processes to stop, then stop the monitor processes and exit.
wait \$SRV
wait \$MID
shutdown
exit
eof
. ./goshellfilter
tcheck $xcli

