////
/**
* @@@ START COPYRIGHT @@@
*
* Licensed to the Apache Software Foundation (ASF) under one
* or more contributor license agreements.  See the NOTICE file
* distributed with this work for additional information
* regarding copyright ownership.  The ASF licenses this file
* to you under the Apache License, Version 2.0 (the
* "License"); you may not use this file except in compliance
* with the License.  You may obtain a copy of the License at
*
*   http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing,
* software distributed under the License is distributed on an
* "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
* KIND, either express or implied.  See the License for the
* specific language governing permissions and limitations
* under the License.
*
* @@@ END COPYRIGHT @@@
  */
////

= odb as a Query Driver (Technology Preview)

== Getting CSV Output
It’s often handy to get a CSV output ready to be imported into your spreadsheet while running performance tests. You can easily get this kind
of output with `–c` odb option.

*Example*

```
$ ./odb64luo -u mauro -p xxx -d pglocal -x 3:"select count(*) from tpch.region" \
-f 5:Q01.sql -f 3:Q02.sql -T 4 -q –c
```

This command runs:

* Three copies of the `select count(*): -x 3:”select count(*) from tpch.region”`
* Five copies of `Q01.sql: -f 5:Q01.sql`
* Three copies of `Q02: -f 3:Q02.sql`
* Queuing the resulting 11 executions into four threads: `-T 4`
* Omitting query text and query results (`-q` is equivalent to `–q all`): `-q`
* Printing a CSV output: `–c`

<<<
The command produces the following output:

```

odb [2011-12-12 08:08:43]: starting (4) threads...
Thread id,Proc id,Thread Exec#,Script
Cmd#,File,Label,Command,Rows,Rsds,Prepare(s),Exec(s),1st
Fetch(s),Fetch(s),Total(s),STimeline,ETimeline
1,1,0,0,(none),,"select count() from tpch.region",1,20,0.000,0.109,0.000,0.000,0.109,94,203
0,0,0,0,(none),,"select count() from tpch.region",1,20,0.000,0.125,0.000,0.000,0.125,94,219
2,2,0,0,(none),,"select count() from tpch.region",1,20,0.000,0.109,0.000,0.000,0.109,110,219
2,6,1,0,Q01.sql,,"SELECT L_RETURNFLAG, L_LINESTATUS,SUM(L_QUANTITY)>",4,234,0.000,136.297,0.000,0.000,136.297,141,136438
2,10,2,0,Q02.sql,,"SELECT S_ACCTBAL, S_NAME, N_NAME,P_PARTKEY,P_MF>",0,274,0.000,0.468,0.000,0.016,0.484,136438,136922
0,4,1,0,Q01.sql,,"SELECT L_RETURNFLAG, L_LINESTATUS,SUM(L_QUANTITY)>",4,234,0.000,139.667,0.016,0.016,139.683,0,139683
0,8,2,0,Q02.sql,,"SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY,P_MFG>",0,274,0.000,0.015,0.000,0.000,0.015,139683,139698
1,5,1,0,Q01.sql,,"SELECT L_RETURNFLAG, L_LINESTATUS,SUM(L_QUANTITY)>",4,234,0.000,144.347,0.015,0.015,144.362,141,144503
1,9,2,0,Q02.sql,,"SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY,P_MFG>",0,274,0.000,0.000,0.000,0.016,0.016,144503,144519
3,3,0,0,Q01.sql,,"SELECT L_RETURNFLAG, L_LINESTATUS,SUM(L_QUANTITY)>",4,234,0.000,144.394,0.016,0.016,144.410,390,144800
3,7,1,0,Q01.sql,,"SELECT L_RETURNFLAG, L_LINESTATUS,SUM(L_QUANTITY)>",4,234,0.000,69.373,0.000,0.000,69.373,144800,214173
odb statistics:
        Init timestamp: 2011-12-12 08:08:42
        Start timestamp: 2011-12-12 08:08:43
        End timestamp: 2011-12-12 08:12:17
	Elapsed [Start->End] (s): 214.173
----
```

<<<
The CSV output columns have the following meaning:

[cols="30%,70%",options="header"]
|===
| Column         | Meaning
| `Thread ID`    | Thread ID. Number of threads limited to 4 &#8212;> thread id values are 0, 1, 2, 3
| `Proc ID`      | Execution number. 11 executions in the 0-10 range.
| `Thread Exec#` | Progressive number (starting from 0) of execution for a specific thread.
| `Script Cmd#`  | If your script contains multiple SQL statement, then they are numbered starting from zero.
| `File`         | Script file name or `(null)` for `–x` commands.
| `Label`        | The label assigned though `set qlabel` in the scripts.
| `Command`      | First 30 characters of the SQL command. It will end with `>` if the command text was truncated.
| `Rows`         | The number of returned rows. Not printed if you used `–q`.
| `Rsds`         | Record Set Display Size. Gives you an idea of _how big_ the result set is.
| `Prepare(s)`   | Prepare (compile) time in seconds.
| `Exec(s)`      | Execution time in seconds.
| `1st Fetch(s)` | Time needed to fetch the first row in seconds.
| `Fetch(s)`     | Total Fetch time in seconds.
| `Total(s)`     | Total query elapsed time from prepare to fetch in seconds.
| `Stimeline`    | Queries start time line in milliseconds.
| `Etimeline`    | Queries end time line in milliseconds.
|===

<<<
== Assign Label to a Query

Sometimes it’s not easy to recognize a query by reading the first 30 characters. Therefore, odb lets you
assign a label to a generic query using:

```
SET QLABEL <label>
```

*Example*

```
~/Devel/odb $ cat script.sql

-- Trafodion TPC-H Query 1 SET QLABEL Q01
SELECT
   L_RETURNFLAG
 , L_LINESTATUS
 , SUM(L_QUANTITY) AS SUM_QTY
 ...
 
-- TPC-H/TPC-R Minimum Cost Supplier Query (Q2)
SET QLABEL Q02
SELECT
   S_ACCTBAL
   , S_NAME
   ...
```

Running this script includes the Query Label in the CSV output:

```
~/Devel/odb $ ./odb64luo -u mauro -p xxx -d pglocal -f script.sql -q -c

odb [2011-12-12 09:06:28]: starting (1) threads...
Thread id,Proc id,Thread Exec#,Script
Cmd#,File,Label,Command,Rows,Rsds,Prepare(s),Exec(s),1st
Fetch(s),Fetch(s),Total(s),STimeline,ETimeline
0,0,0,0,script.sql,Q01,"SELECT L_RETURNFLAG, L_LINESTATUS,
SUM(L_QUANTITY)>",4,234,0.000,43.102,0.000,0.000,43.102,0,43102
0,0,0,1,script.sql,Q02,"SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY,
P_MFG>",0,274,0.000,0.016,0.000,0.000,0.016,43102,43118
odb statistics:
        Init timestamp: 2011-12-12 09:06:28
        Start timestamp: 2011-12-12 09:06:28
        End timestamp: 2011-12-12 09:07:11
	Elapsed [Start->End] (s): 43.118

```

<<<
[[query_driver_all_scripts_path]]
== Run All Scripts With a Given Path

Using `-S <path>` or `-P <path>` options you can run all scripts with a given path
(for example, all files in a directory) either serially (`-S`) or in parallel (`-P`).

Both options let you to use *_multiplying factors_* to run all scripts multiple times.
This multiplying factors are defined with a `<number>:` preceding the script path.

*Examples*

[cols="40%,60%",options="header",]
|===
| odb Command Line                             | Action
| `odb64luo -S ./test/queries/*.sql - c -q`    | Executes *serially* all scripts with extension `.sql` under
`./test/queries/` providing CSV type output (`-c`) and omitting query output (`-q`).
| `odb64luo -P test/queries/* -T 50 - c -q`    | Runs *in parallel* all files under `test/queries/` using 50 threads
(ODBC connections) (`-T 50`), with CSV output (`-c`) and omitting query output (`-q`).
| `odb64luo -P 3: test/queries/* -T 3 -c -q`   | Runs *in parallel three times (`3:`)* all files under `test/queries/`
using three threads (ODBC connections) (`-T 3`), with CSV output (`-c`) and omitting query output (`-q`).
Scripts will be assigned to threads using *_standard assignment_*.
| `odb64luo -P -3: test/queries/* -T 3 -c -q`  | Runs *in parallel three times (`-3:`)* all files under `test/queries/`
using three threads (ODBC connections) (`-T 3`), with CSV type output (`-c`) and omitting query output (`-q`).
Scripts will be assigned to threads using *_round-robin assignment_*.
|===

To understand the difference between *standard* and *round-robin* assignments, imagine you have four scripts in
the target path. This is how the executions will be assigned to threads:

[cols="16%,14%,14%,14%,14%,14%,14%"]
|===
| 3+^h| Standard Assignment (es. -P 3:) 3+^h| Round-Robin Assignment (es. -P -3:)
| h| Thread 1 h| Thread 2 h| Thread 3 h| Thread 1 h| Thread 2 h| Thread 3 
| nth execution | &#8230;           | &#8230;           |               | &#8230;           | &#8230;           | 
| 4th execution | `Script4.sql` | `Script4.sql` | `&#8230;`         | `Script2.sql` | `Script3.sql` | `&#8230;`
| 3rd execution | `Script3.sql` | `Script3.sql` | `Script3.sql` | `Script3.sql` | `Script4.sql` | `Script1.sql`
| 2nd execution | `Script2.sql` | `Script2.sql` | `Script2.sql` | `Script4.sql` | `Script1.sql` | `Script2.sql`
| 1st execution | `Script1.sql` | `Script1.sql` | `Script1.sql` | `Script1.sql` | `Script2.sql` | `Script3.sql`
|===

<<<
== Randomizing Execution Order

You can use the `-Z` option to _shuffle_ the odb internal execution table.
This way the execution order is not predictable.

*Examples*

[cols="45%,55%",options="header"]
|===
| odb Command Line                                  | Action
| `odb64luo&#8230; -S 3: test/queries/* -Z -c –q`       | Executes three times (`3:`) all files in the `test/queries` directory
serially (`-S`) and in random order (`-Z`).
| `odb64luo&#8230; -P 3: test/queries/* -Z –T 5 - c -q` | Executes three times (`3:`) all files in the `test/queries` directory in
parallel (`-P`), using five threads (`-T 5`) and in random order (`-Z`).
|===

== Defining a Timeout

You can stop odb after a given timeout (assuming the execution is not already completed) using `-maxtime <seconds>` option.

*Example*

```
~/Devel/odb $ ./odb64luo -S /home/mauro/scripts/*.sql –maxtime 7200
```

The command executes, *serially,*( all scripts with extension `.sql` under
`/home/mauro/scripts/`; if the execution is not completed after two hours (7200 seconds), then odb stops.

<<<
== Simulating User Thinking Time

You can simulate user *_thinking time_* using the `-ttime <delay>` option.
This argument introduces a `<delay>` millisecond pause between two consecutive executions in the same thread.

*Example*

```
~/src/C/odb $ ./odb64luo -f 5:script1.sql -c -q -ttime 75 -T 2
```

This command runs five times `script1.sql` using two threads. Each thread waits 75 milliseconds before starting
the next execution within a thread. You can also use a *_random thinking time_* in a given `min:max` range.

*Example*

The following command starts commands within a thread with a random delay between 50 and 500 milliseconds:

```
~/src/C/odb $ ./odb64luo -f 5:script1.sql -c -q -ttime 50:500 -T 2
```

== Starting Threads Gracefully

You might want to wait a little before starting the next thread. This can be obtained using the `-delay` option.

*Example*

```
~/src/C/odb $ ./odb64luo -f 5:script1.sql -c -q -delay 200 -T 2
```

This command runs five times `script1.sql` using two threads. Each thread will be started 200 milliseconds after the other.

NOTE: `-delay` introduces a delay during threads start-up while `–ttime` introduces a delay between one command and another within the same
thread.

<<<
== Re-looping a Given Workload

Using `-L` option you can re-loop the workload defined through `-x`, `-f`, `-P`, and `-S` commands a given number of times.
Each thread will re-loop the same number of times.

*Example*

```
~/src/C/odb $ *./*odb64luo -f 5:script1.sql -c -q -M 75 -T 2 -L 3
```

re-loops three times (`-L 3`) the same five executions, using two threads (`-T 2`) with a 75 millisecond pause (`-M 75`) between two
consecutive executions in the same thread.

