/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_trafodion_sql_udr_UDR */

#ifndef _Included_org_trafodion_sql_udr_UDR
#define _Included_org_trafodion_sql_udr_UDR
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_trafodion_sql_udr_UDR
 * Method:    SpInfoGetNextRowJava
 * Signature: ([BILorg/trafodion/sql/udr/UDR/QueueStateInfo;)V
 */
JNIEXPORT void JNICALL Java_org_trafodion_sql_udr_UDR_SpInfoGetNextRowJava
  (JNIEnv *, jobject, jbyteArray, jint, jobject);

/*
 * Class:     org_trafodion_sql_udr_UDR
 * Method:    SpInfoEmitRowJava
 * Signature: ([BILorg/trafodion/sql/udr/UDR/QueueStateInfo;)V
 */
JNIEXPORT void JNICALL Java_org_trafodion_sql_udr_UDR_SpInfoEmitRowJava
  (JNIEnv *, jobject, jbyteArray, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
