#! /bin/sh
# @@@ START COPYRIGHT @@@
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# @@@ END COPYRIGHT @@@

# Like the pattern-masking of QACOMP, here we filter out such stuff as
# timestamps and generated identifiers.  Called by the runregr script
# before doing diff.

fil=$1
if [ "$fil" = "" ]; then
  echo "Usage: $0 filename"
  exit 1
fi

sed " 
s/\/\* ObjectUID = *[0-9]*/ObjectUID = <UID removed>/g
s/est_memory_per_node[ ]*[\.]* .*/est_memory_per_node... removed/g
" $fil
