////
/**
* @@@ START COPYRIGHT @@@
*
* Licensed to the Apache Software Foundation (ASF) under one
* or more contributor license agreements.  See the NOTICE file
* distributed with this work for additional information
* regarding copyright ownership.  The ASF licenses this file
* to you under the Apache License, Version 2.0 (the
* "License"); you may not use this file except in compliance
* with the License.  You may obtain a copy of the License at
*
*   http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing,
* software distributed under the License is distributed on an
* "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
* KIND, either express or implied.  See the License for the
* specific language governing permissions and limitations
* under the License.
*
* @@@ END COPYRIGHT @@@
  */
////

[[bulk-unload]]
= Bulk Unload

The http://trafodion.apache.org/docs/sql_reference/index.html#unload_statement[UNLOAD] statement is a
Trafodion extension that exports data from Trafodion tables into an HDFS location that you specify. 
Refer to the http://trafodion.apache.org/docs/sql_reference/index.html#unload_statement[Trafodion SQL Reference Manual]
for complete documentation.

The extracted data can be either compressed or uncompressed based on what you choose. 
UNLOAD performs multiple steps based on the options you give; for example:

* If using snapshot scan:
** Get list of Trafodion tables from the query plan.
** Create/verify snapshots.

* Purge target location, if specified

* Extract: 
** Copy table data to data files.
** Non-compressed is straight copy.
** Compressed means compression takes place while writing data (no extra step)

* Merge Data Files if specified

*Example*

This example shows how the UNLOAD statement extracts data from a
Trafodion table, `TRAFODION.HBASE.CUSTOMER_DEMOGRAPHICS`, into an HDFS
folder, `/bulkload/customer_demographics`:

```
>>UNLOAD
+>WITH PURGEDATA FROM TARGET
+>MERGE FILE 'merged_customer_demogs.gz' OVERWRITE
+>COMPRESSION GZIP
+>INTO '/bulkload/customer_demographics'
+>SELECT * FROM trafodion.hbase.customer_demographics
+><<+ cardinality 10e10 ,+ cardinality 10e10 >>;
Task: UNLOAD Status: Started
Task: EMPTY TARGET Status: Started
Task: EMPTY TARGET Status: Ended ET: 00:00:00.014
Task: EXTRACT Status: Started
       Rows Processed: 200000
Task: EXTRACT Status: Ended ET: 00:00:04.743 Task: MERGE FILES Status: Started
Task: MERGE FILES Status: Ended ET: 00:00:00.063

--- 200000 row(s) unloaded.
```
